services:
  mysql:
    image: mysql:8.4
    container_name: auto_admin_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auto_admin_test
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: auto_admin_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: auto_admin_client
    restart: unless-stopped
    ports:
      - "5177:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: auto_admin_server 
    restart: unless-stopped
    ports:
      - "5180:5174"
    volumes:
      - ./server:/app
      - server_node_modules:/app/node_modules
    environment:
      - Auto_Admin__PORT=5174
      - Auto_Admin__HOST=0.0.0.0
      - Auto_Admin__NODE_ENV=development
    depends_on:
      - mysql
    env_file: ./server/.env

volumes:
  mysql_data:
  client_node_modules:
  server_node_modules: