services:
  mysql:
    image: mysql:8.4
    container_name: auto_admin_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auto_admin_test
      # MYSQL_ONETIME_PASSWORD: "yes"
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: auto_admin_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - mysql

  client:
    build: ./client
    container_name: auto_admin_client
    restart: unless-stopped
    ports:
      - "5177:5173" # Пробрасываем порт React наружу в Windows
    volumes:
      - ./client:/app # Монтируем код, чтобы изменения в файлах сразу отражались в браузере (Hot Reload)
      - /app/node_modules # Изолируем node_modules внутри контейнера, чтобы не было конфликтов с Windows/WSL
    environment:
      - WATCHPACK_POLLING=true # Помогает Hot Reload стабильно работать внутри WSL/Docker
    depends_on:
      - mysql
  
  server:
    build: ./server
    container_name: auto_admin_server
    restart: unless-stopped
    ports:
      - "5180:5174" # Пробрасываем порт Node.js наружу в Windows
    volumes:
      - ./server:/app # Монтируем код для Hot Reload
      - /app/node_modules # Изолируем зависимости
    environment:
      - WATCHPACK_POLLING=true # Помогает Hot Reload в WSL
      - PORT=5174              # <-- Указываем серверу слушать нужный порт!
      - HOST=0.0.0.0           # <-- Разрешаем запросы снаружи контейнера!
    depends_on:
      - mysql


volumes:
  mysql_data:
