export const ERROR_CODES = {
    COMMON_BAD_REQUEST: 'COMMON.BAD_REQUEST',
    COMMON_UNAUTHORIZED: 'COMMON.UNAUTHORIZED',
    COMMON_FORBIDDEN: 'COMMON.FORBIDDEN',
    COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',
    COMMON_CONFLICT: 'COMMON.CONFLICT',
    COMMON_TOO_MANY_REQUESTS: 'COMMON.TOO_MANY_REQUESTS',
    COMMON_VALIDATION_FAILED: 'COMMON.VALIDATION_FAILED',
    COMMON_INTERNAL_ERROR: 'COMMON.INTERNAL_ERROR',

    AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',
    AUTH_SESSION_INVALID: 'AUTH.SESSION_INVALID',
    AUTH_TOO_MANY_ATTEMPTS: 'AUTH.TOO_MANY_ATTEMPTS',

    INSTALL_INVALID_SETUP_TOKEN: 'INSTALL.INVALID_SETUP_TOKEN',
    INSTALL_DATABASE_CONNECTION_FAILED: 'INSTALL.DATABASE_CONNECTION_FAILED',
    INSTALL_DATABASE_CONFIGURATION_NOT_ALLOWED: 'INSTALL.DATABASE_CONFIGURATION_NOT_ALLOWED',
    INSTALL_MIGRATIONS_ALREADY_COMPLETED: 'INSTALL.MIGRATIONS_ALREADY_COMPLETED',
    INSTALL_MIGRATIONS_ALREADY_RUNNING: 'INSTALL.MIGRATIONS_ALREADY_RUNNING',
    INSTALL_MIGRATION_VERSION_CONFLICT: 'INSTALL.MIGRATION_VERSION_CONFLICT',
    INSTALL_ADMIN_ALREADY_CREATED: 'INSTALL.ADMIN_ALREADY_CREATED',
    INSTALL_ADMIN_ROLE_NOT_FOUND: 'INSTALL.ADMIN_ROLE_NOT_FOUND',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];