export const ERROR_CODES = {
    COMMON_BAD_REQUEST: 'COMMON.BAD_REQUEST',   // Неверный запрос
    COMMON_UNAUTHORIZED: 'COMMON.UNAUTHORIZED', // Не авторизован
    COMMON_FORBIDDEN: 'COMMON.FORBIDDEN',   // Отказано в доступе
    COMMON_NOT_FOUND: 'COMMON.NOT_FOUND',   // Не найдено
    COMMON_CONFLICT: 'COMMON.CONFLICT', // Конфликт
    COMMON_TOO_MANY_REQUESTS: 'COMMON.TOO_MANY_REQUESTS',   // Слишком много запросов
    COMMON_VALIDATION_FAILED: 'COMMON.VALIDATION_FAILED',   // Ошибка валидации
    COMMON_INTERNAL_ERROR: 'COMMON.INTERNAL_ERROR', // Внутренняя ошибка

    AUTH_INVALID_CREDENTIALS: 'AUTH.INVALID_CREDENTIALS',   // Неверные учетные данные
    AUTH_SESSION_INVALID: 'AUTH.SESSION_INVALID',   // Неверная сессия
    AUTH_TOO_MANY_ATTEMPTS: 'AUTH.TOO_MANY_ATTEMPTS',   // Слишком много попыток

    INSTALL_INVALID_SETUP_TOKEN: 'INSTALL.INVALID_SETUP_TOKEN', // Неверный токен настройки
    INSTALL_DATABASE_CONNECTION_FAILED: 'INSTALL.DATABASE_CONNECTION_FAILED',   // Ошибка подключения к базе данных
    INSTALL_DATABASE_CONFIGURATION_NOT_ALLOWED: 'INSTALL.DATABASE_CONFIGURATION_NOT_ALLOWED',   // Конфигурация базы данных не разрешена
    INSTALL_MIGRATIONS_ALREADY_COMPLETED: 'INSTALL.MIGRATIONS_ALREADY_COMPLETED',   // Миграции уже завершены
    INSTALL_MIGRATIONS_ALREADY_RUNNING: 'INSTALL.MIGRATIONS_ALREADY_RUNNING',   // Миграции уже запущены
    INSTALL_MIGRATION_VERSION_CONFLICT: 'INSTALL.MIGRATION_VERSION_CONFLICT',   // Конфликт версий миграций
    INSTALL_ADMIN_ALREADY_CREATED: 'INSTALL.ADMIN_ALREADY_CREATED', // Администратор уже создан
    INSTALL_ADMIN_ROLE_NOT_FOUND: 'INSTALL.ADMIN_ROLE_NOT_FOUND',   // Роль администратора не найдена

    VALIDATION_REQUIRED: 'VALIDATION.REQUIRED', // Обязательное поле
    VALIDATION_INVALID_TYPE: 'VALIDATION.INVALID_TYPE',   // Неверный тип
    VALIDATION_STRING_TOO_SHORT: 'VALIDATION.STRING_TOO_SHORT', // Слишком короткая строка
    VALIDATION_STRING_TOO_LONG: 'VALIDATION.STRING_TOO_LONG', // Слишком длинная строка
    VALIDATION_NUMBER_TOO_SMALL: 'VALIDATION.NUMBER_TOO_SMALL', // Слишком маленькое число
    VALIDATION_NUMBER_TOO_LARGE: 'VALIDATION.NUMBER_TOO_LARGE', // Слишком большое число
    VALIDATION_PASSWORDS_DO_NOT_MATCH: 'VALIDATION.PASSWORDS_DO_NOT_MATCH', // Пароли не совпадают
    VALIDATION_INVALID_VALUE: 'VALIDATION.INVALID_VALUE', // Неверное значение
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
