export interface IconMeta {
    id: string;
    name: string;
    category: string;
    tags: string[];
    component: string;
}

export const ICONS_CATALOG: IconMeta[] = [
    {
        id: 'menu-hamburger-classic',
        name: 'Classic Hamburger Menu',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'classic', 'lines', 'bars', 'navigation', 'sidebar', 'standard', 'three lines'],
        component: 'menu-hamburger-classic.svg',
    },
    {
        id: 'menu-lines-short-bottom-right',
        name: 'Menu Lines Short Bottom Right',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'bottom right', 'short line', 'navigation', 'sidebar'],
        component: 'menu-lines-short-bottom-right.svg',
    },
    {
        id: 'menu-lines-short-bottom-left',
        name: 'Menu Lines Short Bottom Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'bottom left', 'short line', 'navigation', 'sidebar'],
        component: 'menu-lines-short-bottom-left.svg',
    },
    {
        id: 'menu-lines-short-ends-right',
        name: 'Menu Lines Short Ends Right',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'indent right', 'navigation', 'sidebar'],
        component: 'menu-lines-short-ends-right.svg',
    },
    {
        id: 'menu-lines-short-ends-left',
        name: 'Menu Lines Short Ends Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'indent left', 'navigation', 'sidebar'],
        component: 'menu-lines-short-ends-left.svg',
    },
    {
        id: 'menu-lines-staggered-diagonal',
        name: 'Menu Lines Staggered Diagonal',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'diagonal', 'zigzag', 'navigation', 'sidebar'],
        component: 'menu-lines-staggered-diagonal.svg',
    },
    {
        id: 'menu-lines-descending-left',
        name: 'Menu Lines Descending Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'descending', 'stairs', 'left aligned', 'navigation', 'sort'],
        component: 'menu-lines-descending-left.svg',
    },
    {
        id: 'menu-lines-descending-center',
        name: 'Menu Lines Descending Center',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'descending', 'pyramid', 'funnel', 'filter', 'centered', 'navigation'],
        component: 'menu-lines-descending-center.svg',
    },
    {
        id: 'menu-lines-staggered-rounded',
        name: 'Menu Lines Staggered Rounded',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'rounded', 'tabs', 'navigation', 'sidebar'],
        component: 'menu-lines-staggered-rounded.svg',
    },
    {
        id: 'menu-lines-brush',
        name: 'Menu Lines Brush Stroke',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'brush', 'stroke', 'wavy', 'hand drawn', 'artistic', 'organic', 'bars'],
        component: 'menu-lines-brush.svg',
    },
    {
        id: 'menu-lines-duo-large',
        name: 'Menu Lines Duo Large',
        category: 'navigation',
        tags: ['menu', 'lines', 'duo', 'two lines', 'bars', 'large', 'wide', 'minimalist', 'navigation'],
        component: 'menu-lines-duo-large.svg',
    },
    {
        id: 'menu-lines-duo-medium',
        name: 'Menu Lines Duo Medium',
        category: 'navigation',
        tags: ['menu', 'lines', 'duo', 'two lines', 'bars', 'medium', 'minimalist', 'navigation', 'sidebar'],
        component: 'menu-lines-duo-medium.svg',
    },
    {
        id: 'menu-lines-two-rectangles',
        name: 'Menu Lines Two Rectangles',
        category: 'navigation',
        tags: ['menu', 'lines', 'two lines', 'bars', 'rectangles', 'pixel', 'retro', 'boxes', 'navigation'],
        component: 'menu-lines-two-rectangles.svg',
    },
    {
        id: 'menu-square-lines',
        name: 'Menu Square Lines',
        category: 'navigation',
        tags: ['menu', 'square', 'box', 'frame', 'lines', 'bars', 'button', 'navigation', 'sidebar'],
        component: 'menu-square-lines.svg',
    },
    {
        id: 'menu-bullet-list',
        name: 'Menu Bullet List',
        category: 'navigation',
        tags: ['menu', 'list', 'bullet list', 'items', 'checklist', 'navigation', 'sidebar', 'tasks'],
        component: 'menu-bullet-list.svg',
    },
    {
        id: 'menu-bullet-list-rounded',
        name: 'Menu Bullet List Rounded',
        category: 'navigation',
        tags: ['menu', 'list', 'bullet list', 'rounded', 'dots', 'pills', 'items', 'navigation', 'sidebar'],
        component: 'menu-bullet-list-rounded.svg',
    },
    {
        id: 'menu-board-outline',
        name: 'Menu Board Outline',
        category: 'navigation',
        tags: ['menu', 'board', 'clipboard', 'outline', 'lines', 'dashboard', 'panel', 'billboard', 'navigation'],
        component: 'menu-board-outline.svg',
    },
    {
        id: 'menu-board-solid',
        name: 'Menu Board Solid',
        category: 'navigation',
        tags: ['menu', 'board', 'clipboard', 'solid', 'filled', 'dashboard', 'panel', 'billboard', 'navigation'],
        component: 'menu-board-solid.svg',
    },
    {
        id: 'menu-dialpad-solid',
        name: 'Menu Dialpad Solid',
        category: 'navigation',
        tags: ['menu', 'dialpad', 'keypad', 'numpad', 'dots', 'solid', 'grid', '3x3', 'apps', 'navigation'],
        component: 'menu-dialpad-solid.svg',
    },
    {
        id: 'menu-grid-3x3-squares',
        name: 'Menu Grid 3x3 Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'waffle', 'squares', '3x3', 'nine dots', 'apps', 'dashboard', 'navigation'],
        component: 'menu-grid-3x3-squares.svg',
    },
    {
        id: 'menu-grid-2x2-squares',
        name: 'Menu Grid 2x2 Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'squares', '2x2', 'four squares', 'tiles', 'apps', 'dashboard', 'navigation'],
        component: 'menu-grid-2x2-squares.svg',
    },
    {
        id: 'menu-grid-2x2-circles',
        name: 'Menu Grid 2x2 Circles',
        category: 'navigation',
        tags: ['menu', 'grid', 'circles', 'dots', '2x2', 'four dots', 'apps', 'navigation', 'layout'],
        component: 'menu-grid-2x2-circles.svg',
    },
    {
        id: 'menu-grid-2x2-rounded',
        name: 'Menu Grid 2x2 Rounded Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'rounded', 'squares', 'tiles', '2x2', 'solid', 'apps', 'navigation'],
        component: 'menu-grid-2x2-rounded.svg',
    },
    {
        id: 'menu-grid-2x2-framed',
        name: 'Menu Grid 2x2 Framed Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'framed', 'squares', 'tiles', '2x2', 'outline', 'apps', 'navigation'],
        component: 'menu-grid-2x2-framed.svg',
    },
    {
        id: 'menu-dots-horizontal',
        name: 'Menu Dots Horizontal',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'meatballs', 'more', 'actions', 'options', 'navigation'],
        component: 'menu-dots-horizontal.svg',
    },
    {
        id: 'menu-dots-horizontal-rings',
        name: 'Menu Dots Horizontal Rings',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'rings', 'circles', 'meatballs', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-rings.svg',
    },
    {
        id: 'menu-dots-horizontal-circle',
        name: 'Menu Dots Horizontal Circle',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'circle', 'badge', 'meatballs', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-circle.svg',
    },
    {
        id: 'menu-dots-horizontal-circle-arc',
        name: 'Menu Dots Horizontal Circle Arc',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'circle', 'arc', 'badge', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-circle-arc.svg',
    },
    {
        id: 'menu-dots-horizontal-square',
        name: 'Menu Dots Horizontal Square',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'square', 'rounded', 'frame', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-square.svg',
    },
    {
        id: 'menu-dots-horizontal-square-arc',
        name: 'Menu Dots Horizontal Square Arc',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'square', 'arc', 'corner', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-square-arc.svg',
    },
    {
        id: 'menu-dots-vertical-rings',
        name: 'Menu Dots Vertical Rings',
        category: 'navigation',
        tags: ['menu', 'dots', 'vertical', 'rings', 'circles', 'kebab', 'more', 'actions', 'options', 'overflow'],
        component: 'menu-dots-vertical-rings.svg',
    },
    {
        id: 'menu-options-sharp',
        name: 'Menu Options Sharp',
        category: 'navigation',
        tags: ['menu', 'options', 'tabs', 'sharp', 'rectangles', 'settings', 'bars', 'switches', 'navigation'],
        component: 'menu-options-sharp.svg',
    },
    {
        id: 'menu-options-rounded',
        name: 'Menu Options Rounded',
        category: 'navigation',
        tags: ['menu', 'options', 'tabs', 'rounded', 'capsules', 'pills', 'settings', 'bars', 'navigation'],
        component: 'menu-options-rounded.svg',
    },
    {
        id: 'settings-wrench',
        name: 'Settings Wrench',
        category: 'settings',
        tags: ['settings', 'wrench', 'spanner', 'tools', 'repair', 'maintenance', 'config', 'setup', 'options'],
        component: 'settings-wrench.svg',
    },
    {
        id: 'settings-sliders-dual',
        name: 'Settings Sliders Dual',
        category: 'settings',
        tags: ['settings', 'sliders', 'controls', 'faders', 'adjust', 'filters', 'options', 'preferences', 'configuration', 'horizontal'],
        component: 'settings-sliders-dual.svg',
    },
    {
        id: 'settings-chat',
        name: 'Settings Chat',
        category: 'settings',
        tags: ['settings', 'chat', 'message', 'bubble', 'gear', 'cog', 'communication', 'discussion', 'options'],
        component: 'settings-chat.svg',
    },
    {
        id: 'settings-check',
        name: 'Settings Check',
        category: 'settings',
        tags: ['settings', 'check', 'checkmark', 'done', 'success', 'gear', 'cog', 'complete', 'verified', 'options'],
        component: 'settings-check.svg',
    },
    {
        id: 'settings-gears-dual',
        name: 'Settings Gears Dual',
        category: 'settings',
        tags: ['settings', 'gears', 'dual', 'cogs', 'combination', 'mechanism', 'preferences', 'options', 'system'],
        component: 'settings-gears-dual.svg',
    },
    {
        id: 'settings-laptop',
        name: 'Settings Laptop',
        category: 'settings',
        tags: ['settings', 'laptop', 'computer', 'screen', 'gear', 'cog', 'device', 'hardware', 'preferences', 'system'],
        component: 'settings-laptop.svg',
    },
    {
        id: 'settings-message',
        name: 'Settings Message',
        category: 'settings',
        tags: ['settings', 'message', 'comment', 'bubble', 'balloon', 'gear', 'cog', 'communication', 'options'],
        component: 'settings-message.svg',
    },
    {
        id: 'settings-minimalistic-solid',
        name: 'Settings Minimalistic Solid',
        category: 'settings',
        tags: ['settings', 'minimalistic', 'solid', 'filled', 'gear', 'cog', 'nut', 'preferences', 'options', 'system'],
        component: 'settings-minimalistic-solid.svg',
    },
    {
        id: 'settings-minimalistic-outline',
        name: 'Settings Minimalistic Outline',
        category: 'settings',
        tags: ['settings', 'minimalistic', 'outline', 'stroke', 'gear', 'cog', 'nut', 'preferences', 'options', 'system'],
        component: 'settings-minimalistic-outline.svg',
    },
    {
        id: 'settings-monitor',
        name: 'Settings Monitor',
        category: 'settings',
        tags: ['settings', 'monitor', 'display', 'screen', 'desktop', 'gear', 'cog', 'device', 'system', 'preferences'],
        component: 'settings-monitor.svg',
    },
    {
        id: 'settings-shield',
        name: 'Settings Shield',
        category: 'settings',
        tags: ['settings', 'shield', 'security', 'protection', 'safe', 'privacy', 'gear', 'cog', 'guard', 'options'],
        component: 'settings-shield.svg',
    },
    {
        id: 'settings-gear-solid',
        name: 'Settings Gear Solid',
        category: 'settings',
        tags: ['settings', 'gear', 'solid', 'filled', 'cog', 'classic', 'preferences', 'options', 'configuration', 'system'],
        component: 'settings-gear-solid.svg',
    },
    {
        id: 'settings-gears-circle',
        name: 'Settings Gears Circle',
        category: 'settings',
        tags: ['settings', 'gears', 'circle', 'badge', 'round', 'cogs', 'dual', 'preferences', 'options', 'system'],
        component: 'settings-gears-circle.svg',
    },
    {
        id: 'settings-gear-detailed',
        name: 'Settings Gear Detailed',
        category: 'settings',
        tags: ['settings', 'gear', 'detailed', 'mechanical', 'spokes', 'cog', 'machinery', 'preferences', 'system'],
        component: 'settings-gear-detailed.svg',
    },
    {
        id: 'settings-switches',
        name: 'Settings Switches',
        category: 'settings',
        tags: ['settings', 'switches', 'toggles', 'controls', 'options', 'sliders', 'pills', 'preferences', 'configuration'],
        component: 'settings-switches.svg',
    },
    {
        id: 'settings-tools',
        name: 'Settings Tools',
        category: 'settings',
        tags: ['settings', 'tools', 'wrench', 'screwdriver', 'crossed', 'repair', 'maintenance', 'hardware', 'options'],
        component: 'settings-tools.svg',
    },
    {
        id: 'settings-gear-octagon',
        name: 'Settings Gear Octagon',
        category: 'settings',
        tags: ['settings', 'gear', 'octagon', 'eight-tooth', 'cog', 'solid', 'preferences', 'options', 'system'],
        component: 'settings-gear-octagon.svg',
    },
    {
        id: 'settings-gear-flower',
        name: 'Settings Gear Flower',
        category: 'settings',
        tags: ['settings', 'gear', 'flower', 'rounded', 'petals', 'cog', 'smooth', 'preferences', 'options'],
        component: 'settings-gear-flower.svg',
    },
    {
        id: 'settings-gear-segmented',
        name: 'Settings Gear Segmented',
        category: 'settings',
        tags: ['settings', 'gear', 'segmented', 'dashed', 'cutout', 'outline', 'cog', 'preferences', 'options'],
        component: 'settings-gear-segmented.svg',
    },
    {
        id: 'settings-slider-single',
        name: 'Settings Slider Single',
        category: 'settings',
        tags: ['settings', 'slider', 'single', 'knob', 'line', 'adjust', 'control', 'level', 'preferences', 'options'],
        component: 'settings-slider-single.svg',
    },
    {
        id: 'settings-gear-bullseye',
        name: 'Settings Gear Bullseye',
        category: 'settings',
        tags: ['settings', 'gear', 'bullseye', 'core', 'dot', 'center', 'solid', 'cog', 'preferences', 'system'],
        component: 'settings-gear-bullseye.svg',
    },
    {
        id: 'settings-gear-dot',
        name: 'Settings Gear Dot',
        category: 'settings',
        tags: ['settings', 'gear', 'dot', 'point', 'six-tooth', 'cog', 'outline', 'preferences', 'options'],
        component: 'settings-gear-dot.svg',
    },
    {
        id: 'settings-gear-bold',
        name: 'Settings Gear Bold',
        category: 'settings',
        tags: ['settings', 'gear', 'bold', 'thick', 'heavy', 'cog', 'round teeth', 'preferences', 'options'],
        component: 'settings-gear-bold.svg',
    },
    {
        id: 'settings-gear-smooth',
        name: 'Settings Gear Smooth',
        category: 'settings',
        tags: ['settings', 'gear', 'smooth', 'rounded', 'cog', 'outline', 'ring', 'preferences', 'options'],
        component: 'settings-gear-smooth.svg',
    },
    {
        id: 'settings-gear-outline',
        name: 'Settings Gear Outline',
        category: 'settings',
        tags: ['settings', 'gear', 'outline', 'stroke', 'classic', 'cog', 'preferences', 'options', 'system', 'configuration'],
        component: 'settings-gear-outline.svg',
    },
    {
        id: 'settings-sliders-three',
        name: 'Settings Sliders Three',
        category: 'settings',
        tags: ['settings', 'sliders', 'three', 'controls', 'equalizer', 'faders', 'adjust', 'levels', 'preferences', 'options'],
        component: 'settings-sliders-three.svg',
    },
    {
        id: 'content-article-edit',
        name: 'Content Article Edit',
        category: 'content',
        tags: ['content', 'article', 'edit', 'pencil', 'pen', 'writing', 'document', 'post', 'blog', 'author'],
        component: 'content-article-edit.svg',
    },
    {
        id: 'content-article-preview',
        name: 'Content Article Preview',
        category: 'content',
        tags: ['content', 'article', 'preview', 'card', 'image', 'text', 'newspaper', 'post', 'layout', 'media'],
        component: 'content-article-preview.svg',
    },
    {
        id: 'content-article',
        name: 'Content Article',
        category: 'content',
        tags: ['content', 'article', 'document', 'text', 'lines', 'page', 'post', 'news', 'blog'],
        component: 'content-article.svg',
    },
    {
        id: 'content-book',
        name: 'Content Book',
        category: 'content',
        tags: ['content', 'book', 'author', 'library', 'pages', 'read', 'bookmark', 'novel', 'documentation'],
        component: 'content-book.svg',
    },
    {
        id: 'content-book-open',
        name: 'Content Book Open',
        category: 'content',
        tags: ['content', 'book', 'open', 'brochure', 'magazine', 'read', 'pages', 'catalog', 'literature'],
        component: 'content-book-open.svg',
    },
    {
        id: 'content-context-control',
        name: 'Content Context Control',
        category: 'content',
        tags: ['content', 'context', 'control', 'panel', 'dashboard', 'blocks', 'management', 'layout', 'structure'],
        component: 'content-context-control.svg',
    },
    {
        id: 'content-analytics-user',
        name: 'Content Analytics User',
        category: 'content',
        tags: ['content', 'analytics', 'user', 'dau', 'metrics', 'chart', 'activity', 'audience', 'stats'],
        component: 'content-analytics-user.svg',
    },
    {
        id: 'content-data-document',
        name: 'Content Data Document',
        category: 'content',
        tags: ['content', 'data', 'document', 'sheet', 'table', 'matter', 'records', 'report', 'information'],
        component: 'content-data-document.svg',
    },
    {
        id: 'content-save-disk',
        name: 'Content Save Disk',
        category: 'content',
        tags: ['content', 'save', 'disk', 'diskette', 'floppy', 'guardar', 'storage', 'backup', 'file'],
        component: 'content-save-disk.svg',
    },
    {
        id: 'content-layout-inline',
        name: 'Content Layout Inline',
        category: 'content',
        tags: ['content', 'layout', 'inline', 'wrap', 'text', 'sidebar', 'template', 'alignment', 'format'],
        component: 'content-layout-inline.svg',
    },
    {
        id: 'content-layout-large',
        name: 'Content Layout Large',
        category: 'content',
        tags: ['content', 'layout', 'large', 'hero', 'banner', 'wide', 'full', 'featured', 'block'],
        component: 'content-layout-large.svg',
    },
    {
        id: 'content-layout-left',
        name: 'Content Layout Left',
        category: 'content',
        tags: ['content', 'layout', 'left', 'column', 'sidebar', 'split', 'grid', 'alignment', 'position'],
        component: 'content-layout-left.svg',
    },
    {
        id: 'content-management-tree',
        name: 'Content Management Tree',
        category: 'content',
        tags: ['content', 'management', 'tree', 'cms', 'hierarchy', 'folders', 'files', 'organization', 'system'],
        component: 'content-management-tree.svg',
    },
    {
        id: 'content-management-list',
        name: 'Content Management List',
        category: 'content',
        tags: ['content', 'management', 'list', 'cms', 'items', 'bullets', 'cards', 'catalog', 'records'],
        component: 'content-management-list.svg',
    },
    {
        id: 'content-layout-medium',
        name: 'Content Layout Medium',
        category: 'content',
        tags: ['content', 'layout', 'medium', 'container', 'margins', 'block', 'template', 'card'],
        component: 'content-layout-medium.svg',
    },
    {
        id: 'content-layout-minimal',
        name: 'Content Layout Minimal',
        category: 'content',
        tags: ['content', 'layout', 'minimal', 'compact', 'lines', 'summary', 'snippet', 'text'],
        component: 'content-layout-minimal.svg',
    },
    {
        id: 'content-empty',
        name: 'Content Empty',
        category: 'content',
        tags: ['content', 'empty', 'none', 'blank', 'no content', 'placeholder', 'null', 'void'],
        component: 'content-empty.svg',
    },
    {
        id: 'content-layout-right',
        name: 'Content Layout Right',
        category: 'content',
        tags: ['content', 'layout', 'right', 'column', 'sidebar', 'split', 'grid', 'alignment', 'position'],
        component: 'content-layout-right.svg',
    },
    {
        id: 'content-settings-panel',
        name: 'Content Settings Panel',
        category: 'content',
        tags: ['content', 'settings', 'panel', 'window', 'gear', 'editor', 'preferences', 'configuration', 'admin'],
        component: 'content-settings-panel.svg',
    },
    {
        id: 'content-settings-solid',
        name: 'Content Settings Solid',
        category: 'content',
        tags: ['content', 'settings', 'solid', 'window', 'gear', 'fluent', 'configuration', 'options', 'system'],
        component: 'content-settings-solid.svg',
    },
    {
        id: 'content-layout-side-by-side',
        name: 'Content Layout Side by Side',
        category: 'content',
        tags: ['content', 'layout', 'side by side', 'two columns', 'split', 'dual', 'grid', 'comparison'],
        component: 'content-layout-side-by-side.svg',
    },
    {
        id: 'content-layout-small',
        name: 'Content Layout Small',
        category: 'content',
        tags: ['content', 'layout', 'small', 'narrow', 'compact', 'widget', 'block', 'preview'],
        component: 'content-layout-small.svg',
    },
    {
        id: 'content-feed',
        name: 'Content Feed',
        category: 'content',
        tags: ['content', 'feed', 'card', 'stream', 'posts', 'timeline', 'social', 'media', 'news'],
        component: 'content-feed.svg',
    },
    {
        id: 'content-feed-solid',
        name: 'Content Feed Solid',
        category: 'content',
        tags: ['content', 'feed', 'solid', 'card', 'stream', 'posts', 'timeline', 'social', 'media'],
        component: 'content-feed-solid.svg',
    },
    {
        id: 'content-live-chart',
        name: 'Content Live Chart',
        category: 'content',
        tags: ['content', 'live', 'chart', 'trend', 'analytics', 'stream', 'embedded', 'growth', 'graph'],
        component: 'content-live-chart.svg',
    },
    {
        id: 'basket-wire-mesh',
        name: 'Wire Mesh Basket',
        category: 'basket',
        tags: ['basket', 'cart', 'wire', 'mesh', 'grocery', 'store', 'shop', 'handheld', 'shopping'],
        component: 'basket-wire-mesh.svg',
    },
    {
        id: 'basket-cart-grid',
        name: 'Shopping Cart Grid',
        category: 'basket',
        tags: ['basket', 'cart', 'grid', 'shopping cart', 'supermarket', 'store', 'shop', 'ecommerce', 'trolley'],
        component: 'basket-cart-grid.svg',
    },
    {
        id: 'basket-cart-trolley',
        name: 'Shopping Cart Trolley',
        category: 'basket',
        tags: ['basket', 'cart', 'trolley', 'shopping', 'supermarket', 'store', 'ecommerce', 'buy', 'checkout'],
        component: 'basket-cart-trolley.svg',
    },
    {
        id: 'basket-handheld-lines',
        name: 'Handheld Basket Slats',
        category: 'basket',
        tags: ['basket', 'cart', 'handheld', 'slats', 'lines', 'grocery', 'market', 'store', 'shopping'],
        component: 'basket-handheld-lines.svg',
    },
    {
        id: 'basket-cart-speed',
        name: 'Speed Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'speed', 'fast', 'express', 'delivery', 'shopping', 'ecommerce', 'quick buy'],
        component: 'basket-cart-speed.svg',
    },
    {
        id: 'basket-handheld-dual-handle',
        name: 'Dual Handle Basket',
        category: 'basket',
        tags: ['basket', 'cart', 'dual handle', 'handles', 'grocery', 'shopping', 'store', 'supermarket', 'handheld'],
        component: 'basket-handheld-dual-handle.svg',
    },
    {
        id: 'basket-cart-simple',
        name: 'Simple Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'simple', 'minimal', 'shopping cart', 'store', 'shop', 'ecommerce', 'checkout'],
        component: 'basket-cart-simple.svg',
    },
    {
        id: 'basket-cart-shelf',
        name: 'Shopping Cart Shelf',
        category: 'basket',
        tags: ['basket', 'cart', 'shelf', 'rack', 'tray', 'shopping cart', 'supermarket', 'store', 'trolley'],
        component: 'basket-cart-shelf.svg',
    },
    {
        id: 'basket-cart-arrow-down',
        name: 'Cart Arrow Down',
        category: 'basket',
        tags: ['basket', 'cart', 'arrow down', 'add to cart', 'put in', 'download', 'insert', 'shopping', 'ecommerce'],
        component: 'basket-cart-arrow-down.svg',
    },
    {
        id: 'basket-cart-arrow-up',
        name: 'Cart Arrow Up',
        category: 'basket',
        tags: ['basket', 'cart', 'arrow up', 'remove from cart', 'upload', 'checkout', 'export', 'shopping', 'ecommerce'],
        component: 'basket-cart-arrow-up.svg',
    },
    {
        id: 'basket-cart-check-outline',
        name: 'Cart Check Outline',
        category: 'basket',
        tags: ['basket', 'cart', 'check', 'checkmark', 'approved', 'success', 'done', 'shopping cart', 'ecommerce'],
        component: 'basket-cart-check-outline.svg',
    },
    {
        id: 'basket-cart-check-solid',
        name: 'Cart Check Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'check', 'checkmark', 'solid', 'complete', 'success', 'order', 'shopping cart'],
        component: 'basket-cart-check-solid.svg',
    },
    {
        id: 'basket-cart-check',
        name: 'Cart Check',
        category: 'basket',
        tags: ['basket', 'cart', 'check', 'checkmark', 'tick', 'verified', 'shopping', 'store', 'ecommerce'],
        component: 'basket-cart-check.svg',
    },
    {
        id: 'basket-cart-cross-solid',
        name: 'Cart Cross Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'cross', 'x', 'cancel', 'remove', 'delete', 'solid', 'shopping cart'],
        component: 'basket-cart-cross-solid.svg',
    },
    {
        id: 'basket-round-arrow-down',
        name: 'Round Cart Arrow Down',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'arrow down', 'add', 'put in', 'shopping', 'ecommerce'],
        component: 'basket-round-arrow-down.svg',
    },
    {
        id: 'basket-round-empty',
        name: 'Round Cart Empty',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'empty', 'clear', 'shopping cart', 'ecommerce', 'minimal'],
        component: 'basket-round-empty.svg',
    },
    {
        id: 'basket-solid-fill',
        name: 'Solid Fill Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'solid', 'fill', 'loaded', 'package', 'full', 'shopping cart', 'ecommerce'],
        component: 'basket-solid-fill.svg',
    },
    {
        id: 'basket-round-fill',
        name: 'Round Cart Fill',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'fill', 'solid', 'loaded', 'item', 'shopping'],
        component: 'basket-round-fill.svg',
    },
    {
        id: 'basket-large-minimal',
        name: 'Large Cart Minimal',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'wide', 'minimal', 'solar', 'modern', 'shopping cart', 'ecommerce'],
        component: 'basket-large-minimal.svg',
    },
    {
        id: 'basket-large-slats',
        name: 'Large Cart Slats',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'slats', 'diagonal', 'solar', 'shopping cart', 'supermarket', 'ecommerce'],
        component: 'basket-large-slats.svg',
    },
    {
        id: 'basket-large-bars-solid',
        name: 'Large Cart Bars Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'bars', 'solid', 'vertical', 'solar', 'shopping cart', 'supermarket'],
        component: 'basket-large-bars-solid.svg',
    },
    {
        id: 'basket-large-bars',
        name: 'Large Cart Bars',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'bars', 'outline', 'vertical', 'solar', 'shopping cart', 'supermarket'],
        component: 'basket-large-bars.svg',
    },
    {
        id: 'basket-large-outline',
        name: 'Large Cart Outline',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'outline', 'clean', 'solar', 'minimalist', 'shopping cart', 'ecommerce'],
        component: 'basket-large-outline.svg',
    },
    {
        id: 'basket-large-dash',
        name: 'Large Cart Dash',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'dash', 'solar', 'modern', 'shopping cart', 'store', 'ecommerce'],
        component: 'basket-large-dash.svg',
    },
    {
        id: 'basket-cart-minus',
        name: 'Cart Minus',
        category: 'basket',
        tags: ['basket', 'cart', 'minus', 'remove', 'subtract', 'delete item', 'shopping', 'ecommerce', 'checkout'],
        component: 'basket-cart-minus.svg',
    },
    {
        id: 'basket-round-plus',
        name: 'Round Cart Plus',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'plus', 'add', 'insert', 'new item', 'shopping'],
        component: 'basket-round-plus.svg',
    },
    {
        id: 'basket-cart-plus-outline',
        name: 'Cart Plus Outline',
        category: 'basket',
        tags: ['basket', 'cart', 'plus', 'outline', 'add to cart', 'insert', 'solar', 'shopping cart', 'ecommerce'],
        component: 'basket-cart-plus-outline.svg',
    },
    {
        id: 'basket-cart-plus',
        name: 'Cart Plus',
        category: 'basket',
        tags: ['basket', 'cart', 'plus', 'add', 'add item', 'shopping', 'store', 'ecommerce', 'buy'],
        component: 'basket-cart-plus.svg',
    },
    {
        id: 'basket-round-handle',
        name: 'Round Cart Handle',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'handle', 'bar', 'shopping cart', 'ecommerce', 'trolley'],
        component: 'basket-round-handle.svg',
    },
    {
        id: 'basket-round-simple',
        name: 'Round Cart Simple',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'simple', 'classic', 'shopping cart', 'ecommerce', 'market'],
        component: 'basket-round-simple.svg',
    },
    {
        id: 'basket-cart-fast',
        name: 'Fast Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'fast', 'quick', 'speed', 'express', 'delivery', 'shopping', 'ecommerce'],
        component: 'basket-cart-fast.svg',
    },
    {
        id: 'basket-cart-classic',
        name: 'Classic Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'classic', 'standard', 'outline', 'store', 'shop', 'ecommerce', 'checkout'],
        component: 'basket-cart-classic.svg',
    },
    {
        id: 'basket-tote-smile',
        name: 'Smile Tote Basket',
        category: 'basket',
        tags: ['basket', 'cart', 'tote', 'smile', 'happy', 'bag', 'grocery', 'shopping', 'friendly'],
        component: 'basket-tote-smile.svg',
    },
    {
        id: 'basket-handheld-solid',
        name: 'Handheld Basket Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'handheld', 'solid', 'grocery', 'supermarket', 'market', 'shopping', 'store'],
        component: 'basket-handheld-solid.svg',
    },
    {
        id: 'basket-trolley-grid',
        name: 'Trolley Grid Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'trolley', 'grid', 'wire', 'supermarket', 'store', 'shopping cart', 'market'],
        component: 'basket-trolley-grid.svg',
    },
    {
        id: 'basket-round-arrow-up',
        name: 'Round Cart Arrow Up',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'arrow up', 'checkout', 'export', 'shopping', 'ecommerce'],
        component: 'basket-round-arrow-up.svg',
    },
    {
        id: 'basket-cart-xmark',
        name: 'Cart X Mark',
        category: 'basket',
        tags: ['basket', 'cart', 'x mark', 'cross', 'remove', 'cancel', 'delete', 'shopping', 'ecommerce'],
        component: 'basket-cart-xmark.svg',
    },
];