export interface IconMeta {
    id: string;
    name: string;
    category: string;
    tags: string[];
    component: string;
}

export const ICONS_CATALOG: IconMeta[] = [
    {
        id: 'menu-hamburger-classic',
        name: 'Classic Hamburger Menu',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'classic', 'lines', 'bars', 'navigation', 'sidebar', 'standard', 'three lines'],
        component: 'menu-hamburger-classic.svg',
    },
    {
        id: 'menu-lines-short-bottom-right',
        name: 'Menu Lines Short Bottom Right',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'bottom right', 'short line', 'navigation', 'sidebar'],
        component: 'menu-lines-short-bottom-right.svg',
    },
    {
        id: 'menu-lines-short-bottom-left',
        name: 'Menu Lines Short Bottom Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'bottom left', 'short line', 'navigation', 'sidebar'],
        component: 'menu-lines-short-bottom-left.svg',
    },
    {
        id: 'menu-lines-short-ends-right',
        name: 'Menu Lines Short Ends Right',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'indent right', 'navigation', 'sidebar'],
        component: 'menu-lines-short-ends-right.svg',
    },
    {
        id: 'menu-lines-short-ends-left',
        name: 'Menu Lines Short Ends Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'indent left', 'navigation', 'sidebar'],
        component: 'menu-lines-short-ends-left.svg',
    },
    {
        id: 'menu-lines-staggered-diagonal',
        name: 'Menu Lines Staggered Diagonal',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'diagonal', 'zigzag', 'navigation', 'sidebar'],
        component: 'menu-lines-staggered-diagonal.svg',
    },
    {
        id: 'menu-lines-descending-left',
        name: 'Menu Lines Descending Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'descending', 'stairs', 'left aligned', 'navigation', 'sort'],
        component: 'menu-lines-descending-left.svg',
    },
    {
        id: 'menu-lines-descending-center',
        name: 'Menu Lines Descending Center',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'descending', 'pyramid', 'funnel', 'filter', 'centered', 'navigation'],
        component: 'menu-lines-descending-center.svg',
    },
    {
        id: 'menu-lines-staggered-rounded',
        name: 'Menu Lines Staggered Rounded',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'rounded', 'tabs', 'navigation', 'sidebar'],
        component: 'menu-lines-staggered-rounded.svg',
    },
    {
        id: 'menu-lines-brush',
        name: 'Menu Lines Brush Stroke',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'brush', 'stroke', 'wavy', 'hand drawn', 'artistic', 'organic', 'bars'],
        component: 'menu-lines-brush.svg',
    },
    {
        id: 'menu-lines-duo-large',
        name: 'Menu Lines Duo Large',
        category: 'navigation',
        tags: ['menu', 'lines', 'duo', 'two lines', 'bars', 'large', 'wide', 'minimalist', 'navigation'],
        component: 'menu-lines-duo-large.svg',
    },
    {
        id: 'menu-lines-duo-medium',
        name: 'Menu Lines Duo Medium',
        category: 'navigation',
        tags: ['menu', 'lines', 'duo', 'two lines', 'bars', 'medium', 'minimalist', 'navigation', 'sidebar'],
        component: 'menu-lines-duo-medium.svg',
    },
    {
        id: 'menu-lines-two-rectangles',
        name: 'Menu Lines Two Rectangles',
        category: 'navigation',
        tags: ['menu', 'lines', 'two lines', 'bars', 'rectangles', 'pixel', 'retro', 'boxes', 'navigation'],
        component: 'menu-lines-two-rectangles.svg',
    },
    {
        id: 'menu-square-lines',
        name: 'Menu Square Lines',
        category: 'navigation',
        tags: ['menu', 'square', 'box', 'frame', 'lines', 'bars', 'button', 'navigation', 'sidebar'],
        component: 'menu-square-lines.svg',
    },
    {
        id: 'menu-bullet-list',
        name: 'Menu Bullet List',
        category: 'navigation',
        tags: ['menu', 'list', 'bullet list', 'items', 'checklist', 'navigation', 'sidebar', 'tasks'],
        component: 'menu-bullet-list.svg',
    },
    {
        id: 'menu-bullet-list-rounded',
        name: 'Menu Bullet List Rounded',
        category: 'navigation',
        tags: ['menu', 'list', 'bullet list', 'rounded', 'dots', 'pills', 'items', 'navigation', 'sidebar'],
        component: 'menu-bullet-list-rounded.svg',
    },
    {
        id: 'menu-board-outline',
        name: 'Menu Board Outline',
        category: 'navigation',
        tags: ['menu', 'board', 'clipboard', 'outline', 'lines', 'dashboard', 'panel', 'billboard', 'navigation'],
        component: 'menu-board-outline.svg',
    },
    {
        id: 'menu-board-solid',
        name: 'Menu Board Solid',
        category: 'navigation',
        tags: ['menu', 'board', 'clipboard', 'solid', 'filled', 'dashboard', 'panel', 'billboard', 'navigation'],
        component: 'menu-board-solid.svg',
    },
    {
        id: 'menu-dialpad-solid',
        name: 'Menu Dialpad Solid',
        category: 'navigation',
        tags: ['menu', 'dialpad', 'keypad', 'numpad', 'dots', 'solid', 'grid', '3x3', 'apps', 'navigation'],
        component: 'menu-dialpad-solid.svg',
    },
    {
        id: 'menu-grid-3x3-squares',
        name: 'Menu Grid 3x3 Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'waffle', 'squares', '3x3', 'nine dots', 'apps', 'dashboard', 'navigation'],
        component: 'menu-grid-3x3-squares.svg',
    },
    {
        id: 'menu-grid-2x2-squares',
        name: 'Menu Grid 2x2 Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'squares', '2x2', 'four squares', 'tiles', 'apps', 'dashboard', 'navigation'],
        component: 'menu-grid-2x2-squares.svg',
    },
    {
        id: 'menu-grid-2x2-circles',
        name: 'Menu Grid 2x2 Circles',
        category: 'navigation',
        tags: ['menu', 'grid', 'circles', 'dots', '2x2', 'four dots', 'apps', 'navigation', 'layout'],
        component: 'menu-grid-2x2-circles.svg',
    },
    {
        id: 'menu-grid-2x2-rounded',
        name: 'Menu Grid 2x2 Rounded Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'rounded', 'squares', 'tiles', '2x2', 'solid', 'apps', 'navigation'],
        component: 'menu-grid-2x2-rounded.svg',
    },
    {
        id: 'menu-grid-2x2-framed',
        name: 'Menu Grid 2x2 Framed Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'framed', 'squares', 'tiles', '2x2', 'outline', 'apps', 'navigation'],
        component: 'menu-grid-2x2-framed.svg',
    },
    {
        id: 'menu-dots-horizontal',
        name: 'Menu Dots Horizontal',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'meatballs', 'more', 'actions', 'options', 'navigation'],
        component: 'menu-dots-horizontal.svg',
    },
    {
        id: 'menu-dots-horizontal-rings',
        name: 'Menu Dots Horizontal Rings',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'rings', 'circles', 'meatballs', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-rings.svg',
    },
    {
        id: 'menu-dots-horizontal-circle',
        name: 'Menu Dots Horizontal Circle',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'circle', 'badge', 'meatballs', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-circle.svg',
    },
    {
        id: 'menu-dots-horizontal-circle-arc',
        name: 'Menu Dots Horizontal Circle Arc',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'circle', 'arc', 'badge', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-circle-arc.svg',
    },
    {
        id: 'menu-dots-horizontal-square',
        name: 'Menu Dots Horizontal Square',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'square', 'rounded', 'frame', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-square.svg',
    },
    {
        id: 'menu-dots-horizontal-square-arc',
        name: 'Menu Dots Horizontal Square Arc',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'square', 'arc', 'corner', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-square-arc.svg',
    },
    {
        id: 'menu-dots-vertical-rings',
        name: 'Menu Dots Vertical Rings',
        category: 'navigation',
        tags: ['menu', 'dots', 'vertical', 'rings', 'circles', 'kebab', 'more', 'actions', 'options', 'overflow'],
        component: 'menu-dots-vertical-rings.svg',
    },
    {
        id: 'menu-options-sharp',
        name: 'Menu Options Sharp',
        category: 'navigation',
        tags: ['menu', 'options', 'tabs', 'sharp', 'rectangles', 'settings', 'bars', 'switches', 'navigation'],
        component: 'menu-options-sharp.svg',
    },
    {
        id: 'menu-options-rounded',
        name: 'Menu Options Rounded',
        category: 'navigation',
        tags: ['menu', 'options', 'tabs', 'rounded', 'capsules', 'pills', 'settings', 'bars', 'navigation'],
        component: 'menu-options-rounded.svg',
    },
    {
        id: 'settings-wrench',
        name: 'Settings Wrench',
        category: 'settings',
        tags: ['settings', 'wrench', 'spanner', 'tools', 'repair', 'maintenance', 'config', 'setup', 'options'],
        component: 'settings-wrench.svg',
    },
    {
        id: 'settings-sliders-dual',
        name: 'Settings Sliders Dual',
        category: 'settings',
        tags: ['settings', 'sliders', 'controls', 'faders', 'adjust', 'filters', 'options', 'preferences', 'configuration', 'horizontal'],
        component: 'settings-sliders-dual.svg',
    },
    {
        id: 'settings-chat',
        name: 'Settings Chat',
        category: 'settings',
        tags: ['settings', 'chat', 'message', 'bubble', 'gear', 'cog', 'communication', 'discussion', 'options'],
        component: 'settings-chat.svg',
    },
    {
        id: 'settings-check',
        name: 'Settings Check',
        category: 'settings',
        tags: ['settings', 'check', 'checkmark', 'done', 'success', 'gear', 'cog', 'complete', 'verified', 'options'],
        component: 'settings-check.svg',
    },
    {
        id: 'settings-gears-dual',
        name: 'Settings Gears Dual',
        category: 'settings',
        tags: ['settings', 'gears', 'dual', 'cogs', 'combination', 'mechanism', 'preferences', 'options', 'system'],
        component: 'settings-gears-dual.svg',
    },
    {
        id: 'settings-laptop',
        name: 'Settings Laptop',
        category: 'settings',
        tags: ['settings', 'laptop', 'computer', 'screen', 'gear', 'cog', 'device', 'hardware', 'preferences', 'system'],
        component: 'settings-laptop.svg',
    },
    {
        id: 'settings-message',
        name: 'Settings Message',
        category: 'settings',
        tags: ['settings', 'message', 'comment', 'bubble', 'balloon', 'gear', 'cog', 'communication', 'options'],
        component: 'settings-message.svg',
    },
    {
        id: 'settings-minimalistic-solid',
        name: 'Settings Minimalistic Solid',
        category: 'settings',
        tags: ['settings', 'minimalistic', 'solid', 'filled', 'gear', 'cog', 'nut', 'preferences', 'options', 'system'],
        component: 'settings-minimalistic-solid.svg',
    },
    {
        id: 'settings-minimalistic-outline',
        name: 'Settings Minimalistic Outline',
        category: 'settings',
        tags: ['settings', 'minimalistic', 'outline', 'stroke', 'gear', 'cog', 'nut', 'preferences', 'options', 'system'],
        component: 'settings-minimalistic-outline.svg',
    },
    {
        id: 'settings-monitor',
        name: 'Settings Monitor',
        category: 'settings',
        tags: ['settings', 'monitor', 'display', 'screen', 'desktop', 'gear', 'cog', 'device', 'system', 'preferences'],
        component: 'settings-monitor.svg',
    },
    {
        id: 'settings-shield',
        name: 'Settings Shield',
        category: 'settings',
        tags: ['settings', 'shield', 'security', 'protection', 'safe', 'privacy', 'gear', 'cog', 'guard', 'options'],
        component: 'settings-shield.svg',
    },
    {
        id: 'settings-gear-solid',
        name: 'Settings Gear Solid',
        category: 'settings',
        tags: ['settings', 'gear', 'solid', 'filled', 'cog', 'classic', 'preferences', 'options', 'configuration', 'system'],
        component: 'settings-gear-solid.svg',
    },
    {
        id: 'settings-gears-circle',
        name: 'Settings Gears Circle',
        category: 'settings',
        tags: ['settings', 'gears', 'circle', 'badge', 'round', 'cogs', 'dual', 'preferences', 'options', 'system'],
        component: 'settings-gears-circle.svg',
    },
    {
        id: 'settings-gear-detailed',
        name: 'Settings Gear Detailed',
        category: 'settings',
        tags: ['settings', 'gear', 'detailed', 'mechanical', 'spokes', 'cog', 'machinery', 'preferences', 'system'],
        component: 'settings-gear-detailed.svg',
    },
    {
        id: 'settings-switches',
        name: 'Settings Switches',
        category: 'settings',
        tags: ['settings', 'switches', 'toggles', 'controls', 'options', 'sliders', 'pills', 'preferences', 'configuration'],
        component: 'settings-switches.svg',
    },
    {
        id: 'settings-tools',
        name: 'Settings Tools',
        category: 'settings',
        tags: ['settings', 'tools', 'wrench', 'screwdriver', 'crossed', 'repair', 'maintenance', 'hardware', 'options'],
        component: 'settings-tools.svg',
    },
    {
        id: 'settings-gear-octagon',
        name: 'Settings Gear Octagon',
        category: 'settings',
        tags: ['settings', 'gear', 'octagon', 'eight-tooth', 'cog', 'solid', 'preferences', 'options', 'system'],
        component: 'settings-gear-octagon.svg',
    },
    {
        id: 'settings-gear-flower',
        name: 'Settings Gear Flower',
        category: 'settings',
        tags: ['settings', 'gear', 'flower', 'rounded', 'petals', 'cog', 'smooth', 'preferences', 'options'],
        component: 'settings-gear-flower.svg',
    },
    {
        id: 'settings-gear-segmented',
        name: 'Settings Gear Segmented',
        category: 'settings',
        tags: ['settings', 'gear', 'segmented', 'dashed', 'cutout', 'outline', 'cog', 'preferences', 'options'],
        component: 'settings-gear-segmented.svg',
    },
    {
        id: 'settings-slider-single',
        name: 'Settings Slider Single',
        category: 'settings',
        tags: ['settings', 'slider', 'single', 'knob', 'line', 'adjust', 'control', 'level', 'preferences', 'options'],
        component: 'settings-slider-single.svg',
    },
    {
        id: 'settings-gear-bullseye',
        name: 'Settings Gear Bullseye',
        category: 'settings',
        tags: ['settings', 'gear', 'bullseye', 'core', 'dot', 'center', 'solid', 'cog', 'preferences', 'system'],
        component: 'settings-gear-bullseye.svg',
    },
    {
        id: 'settings-gear-dot',
        name: 'Settings Gear Dot',
        category: 'settings',
        tags: ['settings', 'gear', 'dot', 'point', 'six-tooth', 'cog', 'outline', 'preferences', 'options'],
        component: 'settings-gear-dot.svg',
    },
    {
        id: 'settings-gear-bold',
        name: 'Settings Gear Bold',
        category: 'settings',
        tags: ['settings', 'gear', 'bold', 'thick', 'heavy', 'cog', 'round teeth', 'preferences', 'options'],
        component: 'settings-gear-bold.svg',
    },
    {
        id: 'settings-gear-smooth',
        name: 'Settings Gear Smooth',
        category: 'settings',
        tags: ['settings', 'gear', 'smooth', 'rounded', 'cog', 'outline', 'ring', 'preferences', 'options'],
        component: 'settings-gear-smooth.svg',
    },
    {
        id: 'settings-gear-outline',
        name: 'Settings Gear Outline',
        category: 'settings',
        tags: ['settings', 'gear', 'outline', 'stroke', 'classic', 'cog', 'preferences', 'options', 'system', 'configuration'],
        component: 'settings-gear-outline.svg',
    },
    {
        id: 'settings-sliders-three',
        name: 'Settings Sliders Three',
        category: 'settings',
        tags: ['settings', 'sliders', 'three', 'controls', 'equalizer', 'faders', 'adjust', 'levels', 'preferences', 'options'],
        component: 'settings-sliders-three.svg',
    },
];