export interface IconMeta {
    id: string;
    name: string;
    category: string;
    tags: string[];
    component: string;
}

export const ICONS_CATALOG: IconMeta[] = [
    {
        id: 'menu-hamburger-classic',
        name: 'Classic Hamburger Menu',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'classic', 'lines', 'bars', 'navigation', 'sidebar', 'standard', 'three lines'],
        component: 'menu-hamburger-classic.svg',
    },
    {
        id: 'menu-lines-short-bottom-right',
        name: 'Menu Lines Short Bottom Right',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'bottom right', 'short line', 'navigation', 'sidebar'],
        component: 'menu-lines-short-bottom-right.svg',
    },
    {
        id: 'menu-lines-short-bottom-left',
        name: 'Menu Lines Short Bottom Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'bottom left', 'short line', 'navigation', 'sidebar'],
        component: 'menu-lines-short-bottom-left.svg',
    },
    {
        id: 'menu-lines-short-ends-right',
        name: 'Menu Lines Short Ends Right',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'indent right', 'navigation', 'sidebar'],
        component: 'menu-lines-short-ends-right.svg',
    },
    {
        id: 'menu-lines-short-ends-left',
        name: 'Menu Lines Short Ends Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'indent left', 'navigation', 'sidebar'],
        component: 'menu-lines-short-ends-left.svg',
    },
    {
        id: 'menu-lines-staggered-diagonal',
        name: 'Menu Lines Staggered Diagonal',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'diagonal', 'zigzag', 'navigation', 'sidebar'],
        component: 'menu-lines-staggered-diagonal.svg',
    },
    {
        id: 'menu-lines-descending-left',
        name: 'Menu Lines Descending Left',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'descending', 'stairs', 'left aligned', 'navigation', 'sort'],
        component: 'menu-lines-descending-left.svg',
    },
    {
        id: 'menu-lines-descending-center',
        name: 'Menu Lines Descending Center',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'descending', 'pyramid', 'funnel', 'filter', 'centered', 'navigation'],
        component: 'menu-lines-descending-center.svg',
    },
    {
        id: 'menu-lines-staggered-rounded',
        name: 'Menu Lines Staggered Rounded',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'bars', 'staggered', 'rounded', 'tabs', 'navigation', 'sidebar'],
        component: 'menu-lines-staggered-rounded.svg',
    },
    {
        id: 'menu-lines-brush',
        name: 'Menu Lines Brush Stroke',
        category: 'navigation',
        tags: ['menu', 'hamburger', 'lines', 'brush', 'stroke', 'wavy', 'hand drawn', 'artistic', 'organic', 'bars'],
        component: 'menu-lines-brush.svg',
    },
    {
        id: 'menu-lines-duo-large',
        name: 'Menu Lines Duo Large',
        category: 'navigation',
        tags: ['menu', 'lines', 'duo', 'two lines', 'bars', 'large', 'wide', 'minimalist', 'navigation'],
        component: 'menu-lines-duo-large.svg',
    },
    {
        id: 'menu-lines-duo-medium',
        name: 'Menu Lines Duo Medium',
        category: 'navigation',
        tags: ['menu', 'lines', 'duo', 'two lines', 'bars', 'medium', 'minimalist', 'navigation', 'sidebar'],
        component: 'menu-lines-duo-medium.svg',
    },
    {
        id: 'menu-lines-two-rectangles',
        name: 'Menu Lines Two Rectangles',
        category: 'navigation',
        tags: ['menu', 'lines', 'two lines', 'bars', 'rectangles', 'pixel', 'retro', 'boxes', 'navigation'],
        component: 'menu-lines-two-rectangles.svg',
    },
    {
        id: 'menu-square-lines',
        name: 'Menu Square Lines',
        category: 'navigation',
        tags: ['menu', 'square', 'box', 'frame', 'lines', 'bars', 'button', 'navigation', 'sidebar'],
        component: 'menu-square-lines.svg',
    },
    {
        id: 'menu-bullet-list',
        name: 'Menu Bullet List',
        category: 'navigation',
        tags: ['menu', 'list', 'bullet list', 'items', 'checklist', 'navigation', 'sidebar', 'tasks'],
        component: 'menu-bullet-list.svg',
    },
    {
        id: 'menu-bullet-list-rounded',
        name: 'Menu Bullet List Rounded',
        category: 'navigation',
        tags: ['menu', 'list', 'bullet list', 'rounded', 'dots', 'pills', 'items', 'navigation', 'sidebar'],
        component: 'menu-bullet-list-rounded.svg',
    },
    {
        id: 'menu-board-outline',
        name: 'Menu Board Outline',
        category: 'navigation',
        tags: ['menu', 'board', 'clipboard', 'outline', 'lines', 'dashboard', 'panel', 'billboard', 'navigation'],
        component: 'menu-board-outline.svg',
    },
    {
        id: 'menu-board-solid',
        name: 'Menu Board Solid',
        category: 'navigation',
        tags: ['menu', 'board', 'clipboard', 'solid', 'filled', 'dashboard', 'panel', 'billboard', 'navigation'],
        component: 'menu-board-solid.svg',
    },
    {
        id: 'menu-dialpad-solid',
        name: 'Menu Dialpad Solid',
        category: 'navigation',
        tags: ['menu', 'dialpad', 'keypad', 'numpad', 'dots', 'solid', 'grid', '3x3', 'apps', 'navigation'],
        component: 'menu-dialpad-solid.svg',
    },
    {
        id: 'menu-grid-3x3-squares',
        name: 'Menu Grid 3x3 Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'waffle', 'squares', '3x3', 'nine dots', 'apps', 'dashboard', 'navigation'],
        component: 'menu-grid-3x3-squares.svg',
    },
    {
        id: 'menu-grid-2x2-squares',
        name: 'Menu Grid 2x2 Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'squares', '2x2', 'four squares', 'tiles', 'apps', 'dashboard', 'navigation'],
        component: 'menu-grid-2x2-squares.svg',
    },
    {
        id: 'menu-grid-2x2-circles',
        name: 'Menu Grid 2x2 Circles',
        category: 'navigation',
        tags: ['menu', 'grid', 'circles', 'dots', '2x2', 'four dots', 'apps', 'navigation', 'layout'],
        component: 'menu-grid-2x2-circles.svg',
    },
    {
        id: 'menu-grid-2x2-rounded',
        name: 'Menu Grid 2x2 Rounded Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'rounded', 'squares', 'tiles', '2x2', 'solid', 'apps', 'navigation'],
        component: 'menu-grid-2x2-rounded.svg',
    },
    {
        id: 'menu-grid-2x2-framed',
        name: 'Menu Grid 2x2 Framed Squares',
        category: 'navigation',
        tags: ['menu', 'grid', 'framed', 'squares', 'tiles', '2x2', 'outline', 'apps', 'navigation'],
        component: 'menu-grid-2x2-framed.svg',
    },
    {
        id: 'menu-dots-horizontal',
        name: 'Menu Dots Horizontal',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'meatballs', 'more', 'actions', 'options', 'navigation'],
        component: 'menu-dots-horizontal.svg',
    },
    {
        id: 'menu-dots-horizontal-rings',
        name: 'Menu Dots Horizontal Rings',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'rings', 'circles', 'meatballs', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-rings.svg',
    },
    {
        id: 'menu-dots-horizontal-circle',
        name: 'Menu Dots Horizontal Circle',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'circle', 'badge', 'meatballs', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-circle.svg',
    },
    {
        id: 'menu-dots-horizontal-circle-arc',
        name: 'Menu Dots Horizontal Circle Arc',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'circle', 'arc', 'badge', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-circle-arc.svg',
    },
    {
        id: 'menu-dots-horizontal-square',
        name: 'Menu Dots Horizontal Square',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'square', 'rounded', 'frame', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-square.svg',
    },
    {
        id: 'menu-dots-horizontal-square-arc',
        name: 'Menu Dots Horizontal Square Arc',
        category: 'navigation',
        tags: ['menu', 'dots', 'horizontal', 'square', 'arc', 'corner', 'more', 'actions', 'options'],
        component: 'menu-dots-horizontal-square-arc.svg',
    },
    {
        id: 'menu-dots-vertical-rings',
        name: 'Menu Dots Vertical Rings',
        category: 'navigation',
        tags: ['menu', 'dots', 'vertical', 'rings', 'circles', 'kebab', 'more', 'actions', 'options', 'overflow'],
        component: 'menu-dots-vertical-rings.svg',
    },
    {
        id: 'menu-options-sharp',
        name: 'Menu Options Sharp',
        category: 'navigation',
        tags: ['menu', 'options', 'tabs', 'sharp', 'rectangles', 'settings', 'bars', 'switches', 'navigation'],
        component: 'menu-options-sharp.svg',
    },
    {
        id: 'menu-options-rounded',
        name: 'Menu Options Rounded',
        category: 'navigation',
        tags: ['menu', 'options', 'tabs', 'rounded', 'capsules', 'pills', 'settings', 'bars', 'navigation'],
        component: 'menu-options-rounded.svg',
    },
    {
        id: 'settings-wrench',
        name: 'Settings Wrench',
        category: 'settings',
        tags: ['settings', 'wrench', 'spanner', 'tools', 'repair', 'maintenance', 'config', 'setup', 'options'],
        component: 'settings-wrench.svg',
    },
    {
        id: 'settings-sliders-dual',
        name: 'Settings Sliders Dual',
        category: 'settings',
        tags: ['settings', 'sliders', 'controls', 'faders', 'adjust', 'filters', 'options', 'preferences', 'configuration', 'horizontal'],
        component: 'settings-sliders-dual.svg',
    },
    {
        id: 'settings-chat',
        name: 'Settings Chat',
        category: 'settings',
        tags: ['settings', 'chat', 'message', 'bubble', 'gear', 'cog', 'communication', 'discussion', 'options'],
        component: 'settings-chat.svg',
    },
    {
        id: 'settings-check',
        name: 'Settings Check',
        category: 'settings',
        tags: ['settings', 'check', 'checkmark', 'done', 'success', 'gear', 'cog', 'complete', 'verified', 'options'],
        component: 'settings-check.svg',
    },
    {
        id: 'settings-gears-dual',
        name: 'Settings Gears Dual',
        category: 'settings',
        tags: ['settings', 'gears', 'dual', 'cogs', 'combination', 'mechanism', 'preferences', 'options', 'system'],
        component: 'settings-gears-dual.svg',
    },
    {
        id: 'settings-laptop',
        name: 'Settings Laptop',
        category: 'settings',
        tags: ['settings', 'laptop', 'computer', 'screen', 'gear', 'cog', 'device', 'hardware', 'preferences', 'system'],
        component: 'settings-laptop.svg',
    },
    {
        id: 'settings-message',
        name: 'Settings Message',
        category: 'settings',
        tags: ['settings', 'message', 'comment', 'bubble', 'balloon', 'gear', 'cog', 'communication', 'options'],
        component: 'settings-message.svg',
    },
    {
        id: 'settings-minimalistic-solid',
        name: 'Settings Minimalistic Solid',
        category: 'settings',
        tags: ['settings', 'minimalistic', 'solid', 'filled', 'gear', 'cog', 'nut', 'preferences', 'options', 'system'],
        component: 'settings-minimalistic-solid.svg',
    },
    {
        id: 'settings-minimalistic-outline',
        name: 'Settings Minimalistic Outline',
        category: 'settings',
        tags: ['settings', 'minimalistic', 'outline', 'stroke', 'gear', 'cog', 'nut', 'preferences', 'options', 'system'],
        component: 'settings-minimalistic-outline.svg',
    },
    {
        id: 'settings-monitor',
        name: 'Settings Monitor',
        category: 'settings',
        tags: ['settings', 'monitor', 'display', 'screen', 'desktop', 'gear', 'cog', 'device', 'system', 'preferences'],
        component: 'settings-monitor.svg',
    },
    {
        id: 'settings-shield',
        name: 'Settings Shield',
        category: 'settings',
        tags: ['settings', 'shield', 'security', 'protection', 'safe', 'privacy', 'gear', 'cog', 'guard', 'options'],
        component: 'settings-shield.svg',
    },
    {
        id: 'settings-gear-solid',
        name: 'Settings Gear Solid',
        category: 'settings',
        tags: ['settings', 'gear', 'solid', 'filled', 'cog', 'classic', 'preferences', 'options', 'configuration', 'system'],
        component: 'settings-gear-solid.svg',
    },
    {
        id: 'settings-gears-circle',
        name: 'Settings Gears Circle',
        category: 'settings',
        tags: ['settings', 'gears', 'circle', 'badge', 'round', 'cogs', 'dual', 'preferences', 'options', 'system'],
        component: 'settings-gears-circle.svg',
    },
    {
        id: 'settings-gear-detailed',
        name: 'Settings Gear Detailed',
        category: 'settings',
        tags: ['settings', 'gear', 'detailed', 'mechanical', 'spokes', 'cog', 'machinery', 'preferences', 'system'],
        component: 'settings-gear-detailed.svg',
    },
    {
        id: 'settings-switches',
        name: 'Settings Switches',
        category: 'settings',
        tags: ['settings', 'switches', 'toggles', 'controls', 'options', 'sliders', 'pills', 'preferences', 'configuration'],
        component: 'settings-switches.svg',
    },
    {
        id: 'settings-tools',
        name: 'Settings Tools',
        category: 'settings',
        tags: ['settings', 'tools', 'wrench', 'screwdriver', 'crossed', 'repair', 'maintenance', 'hardware', 'options'],
        component: 'settings-tools.svg',
    },
    {
        id: 'settings-gear-octagon',
        name: 'Settings Gear Octagon',
        category: 'settings',
        tags: ['settings', 'gear', 'octagon', 'eight-tooth', 'cog', 'solid', 'preferences', 'options', 'system'],
        component: 'settings-gear-octagon.svg',
    },
    {
        id: 'settings-gear-flower',
        name: 'Settings Gear Flower',
        category: 'settings',
        tags: ['settings', 'gear', 'flower', 'rounded', 'petals', 'cog', 'smooth', 'preferences', 'options'],
        component: 'settings-gear-flower.svg',
    },
    {
        id: 'settings-gear-segmented',
        name: 'Settings Gear Segmented',
        category: 'settings',
        tags: ['settings', 'gear', 'segmented', 'dashed', 'cutout', 'outline', 'cog', 'preferences', 'options'],
        component: 'settings-gear-segmented.svg',
    },
    {
        id: 'settings-slider-single',
        name: 'Settings Slider Single',
        category: 'settings',
        tags: ['settings', 'slider', 'single', 'knob', 'line', 'adjust', 'control', 'level', 'preferences', 'options'],
        component: 'settings-slider-single.svg',
    },
    {
        id: 'settings-gear-bullseye',
        name: 'Settings Gear Bullseye',
        category: 'settings',
        tags: ['settings', 'gear', 'bullseye', 'core', 'dot', 'center', 'solid', 'cog', 'preferences', 'system'],
        component: 'settings-gear-bullseye.svg',
    },
    {
        id: 'settings-gear-dot',
        name: 'Settings Gear Dot',
        category: 'settings',
        tags: ['settings', 'gear', 'dot', 'point', 'six-tooth', 'cog', 'outline', 'preferences', 'options'],
        component: 'settings-gear-dot.svg',
    },
    {
        id: 'settings-gear-bold',
        name: 'Settings Gear Bold',
        category: 'settings',
        tags: ['settings', 'gear', 'bold', 'thick', 'heavy', 'cog', 'round teeth', 'preferences', 'options'],
        component: 'settings-gear-bold.svg',
    },
    {
        id: 'settings-gear-smooth',
        name: 'Settings Gear Smooth',
        category: 'settings',
        tags: ['settings', 'gear', 'smooth', 'rounded', 'cog', 'outline', 'ring', 'preferences', 'options'],
        component: 'settings-gear-smooth.svg',
    },
    {
        id: 'settings-gear-outline',
        name: 'Settings Gear Outline',
        category: 'settings',
        tags: ['settings', 'gear', 'outline', 'stroke', 'classic', 'cog', 'preferences', 'options', 'system', 'configuration'],
        component: 'settings-gear-outline.svg',
    },
    {
        id: 'settings-sliders-three',
        name: 'Settings Sliders Three',
        category: 'settings',
        tags: ['settings', 'sliders', 'three', 'controls', 'equalizer', 'faders', 'adjust', 'levels', 'preferences', 'options'],
        component: 'settings-sliders-three.svg',
    },
    {
        id: 'content-article-edit',
        name: 'Content Article Edit',
        category: 'content',
        tags: ['content', 'article', 'edit', 'pencil', 'pen', 'writing', 'document', 'post', 'blog', 'author'],
        component: 'content-article-edit.svg',
    },
    {
        id: 'content-article-preview',
        name: 'Content Article Preview',
        category: 'content',
        tags: ['content', 'article', 'preview', 'card', 'image', 'text', 'newspaper', 'post', 'layout', 'media'],
        component: 'content-article-preview.svg',
    },
    {
        id: 'content-article',
        name: 'Content Article',
        category: 'content',
        tags: ['content', 'article', 'document', 'text', 'lines', 'page', 'post', 'news', 'blog'],
        component: 'content-article.svg',
    },
    {
        id: 'content-book',
        name: 'Content Book',
        category: 'content',
        tags: ['content', 'book', 'author', 'library', 'pages', 'read', 'bookmark', 'novel', 'documentation'],
        component: 'content-book.svg',
    },
    {
        id: 'content-book-open',
        name: 'Content Book Open',
        category: 'content',
        tags: ['content', 'book', 'open', 'brochure', 'magazine', 'read', 'pages', 'catalog', 'literature'],
        component: 'content-book-open.svg',
    },
    {
        id: 'content-context-control',
        name: 'Content Context Control',
        category: 'content',
        tags: ['content', 'context', 'control', 'panel', 'dashboard', 'blocks', 'management', 'layout', 'structure'],
        component: 'content-context-control.svg',
    },
    {
        id: 'content-analytics-user',
        name: 'Content Analytics User',
        category: 'content',
        tags: ['content', 'analytics', 'user', 'dau', 'metrics', 'chart', 'activity', 'audience', 'stats'],
        component: 'content-analytics-user.svg',
    },
    {
        id: 'content-data-document',
        name: 'Content Data Document',
        category: 'content',
        tags: ['content', 'data', 'document', 'sheet', 'table', 'matter', 'records', 'report', 'information'],
        component: 'content-data-document.svg',
    },
    {
        id: 'content-save-disk',
        name: 'Content Save Disk',
        category: 'content',
        tags: ['content', 'save', 'disk', 'diskette', 'floppy', 'guardar', 'storage', 'backup', 'file'],
        component: 'content-save-disk.svg',
    },
    {
        id: 'content-layout-inline',
        name: 'Content Layout Inline',
        category: 'content',
        tags: ['content', 'layout', 'inline', 'wrap', 'text', 'sidebar', 'template', 'alignment', 'format'],
        component: 'content-layout-inline.svg',
    },
    {
        id: 'content-layout-large',
        name: 'Content Layout Large',
        category: 'content',
        tags: ['content', 'layout', 'large', 'hero', 'banner', 'wide', 'full', 'featured', 'block'],
        component: 'content-layout-large.svg',
    },
    {
        id: 'content-layout-left',
        name: 'Content Layout Left',
        category: 'content',
        tags: ['content', 'layout', 'left', 'column', 'sidebar', 'split', 'grid', 'alignment', 'position'],
        component: 'content-layout-left.svg',
    },
    {
        id: 'content-management-tree',
        name: 'Content Management Tree',
        category: 'content',
        tags: ['content', 'management', 'tree', 'cms', 'hierarchy', 'folders', 'files', 'organization', 'system'],
        component: 'content-management-tree.svg',
    },
    {
        id: 'content-management-list',
        name: 'Content Management List',
        category: 'content',
        tags: ['content', 'management', 'list', 'cms', 'items', 'bullets', 'cards', 'catalog', 'records'],
        component: 'content-management-list.svg',
    },
    {
        id: 'content-layout-medium',
        name: 'Content Layout Medium',
        category: 'content',
        tags: ['content', 'layout', 'medium', 'container', 'margins', 'block', 'template', 'card'],
        component: 'content-layout-medium.svg',
    },
    {
        id: 'content-layout-minimal',
        name: 'Content Layout Minimal',
        category: 'content',
        tags: ['content', 'layout', 'minimal', 'compact', 'lines', 'summary', 'snippet', 'text'],
        component: 'content-layout-minimal.svg',
    },
    {
        id: 'content-empty',
        name: 'Content Empty',
        category: 'content',
        tags: ['content', 'empty', 'none', 'blank', 'no content', 'placeholder', 'null', 'void'],
        component: 'content-empty.svg',
    },
    {
        id: 'content-layout-right',
        name: 'Content Layout Right',
        category: 'content',
        tags: ['content', 'layout', 'right', 'column', 'sidebar', 'split', 'grid', 'alignment', 'position'],
        component: 'content-layout-right.svg',
    },
    {
        id: 'content-settings-panel',
        name: 'Content Settings Panel',
        category: 'content',
        tags: ['content', 'settings', 'panel', 'window', 'gear', 'editor', 'preferences', 'configuration', 'admin'],
        component: 'content-settings-panel.svg',
    },
    {
        id: 'content-settings-solid',
        name: 'Content Settings Solid',
        category: 'content',
        tags: ['content', 'settings', 'solid', 'window', 'gear', 'fluent', 'configuration', 'options', 'system'],
        component: 'content-settings-solid.svg',
    },
    {
        id: 'content-layout-side-by-side',
        name: 'Content Layout Side by Side',
        category: 'content',
        tags: ['content', 'layout', 'side by side', 'two columns', 'split', 'dual', 'grid', 'comparison'],
        component: 'content-layout-side-by-side.svg',
    },
    {
        id: 'content-layout-small',
        name: 'Content Layout Small',
        category: 'content',
        tags: ['content', 'layout', 'small', 'narrow', 'compact', 'widget', 'block', 'preview'],
        component: 'content-layout-small.svg',
    },
    {
        id: 'content-feed',
        name: 'Content Feed',
        category: 'content',
        tags: ['content', 'feed', 'card', 'stream', 'posts', 'timeline', 'social', 'media', 'news'],
        component: 'content-feed.svg',
    },
    {
        id: 'content-feed-solid',
        name: 'Content Feed Solid',
        category: 'content',
        tags: ['content', 'feed', 'solid', 'card', 'stream', 'posts', 'timeline', 'social', 'media'],
        component: 'content-feed-solid.svg',
    },
    {
        id: 'content-live-chart',
        name: 'Content Live Chart',
        category: 'content',
        tags: ['content', 'live', 'chart', 'trend', 'analytics', 'stream', 'embedded', 'growth', 'graph'],
        component: 'content-live-chart.svg',
    },
    {
        id: 'basket-wire-mesh',
        name: 'Wire Mesh Basket',
        category: 'basket',
        tags: ['basket', 'cart', 'wire', 'mesh', 'grocery', 'store', 'shop', 'handheld', 'shopping'],
        component: 'basket-wire-mesh.svg',
    },
    {
        id: 'basket-cart-grid',
        name: 'Shopping Cart Grid',
        category: 'basket',
        tags: ['basket', 'cart', 'grid', 'shopping cart', 'supermarket', 'store', 'shop', 'ecommerce', 'trolley'],
        component: 'basket-cart-grid.svg',
    },
    {
        id: 'basket-cart-trolley',
        name: 'Shopping Cart Trolley',
        category: 'basket',
        tags: ['basket', 'cart', 'trolley', 'shopping', 'supermarket', 'store', 'ecommerce', 'buy', 'checkout'],
        component: 'basket-cart-trolley.svg',
    },
    {
        id: 'basket-handheld-lines',
        name: 'Handheld Basket Slats',
        category: 'basket',
        tags: ['basket', 'cart', 'handheld', 'slats', 'lines', 'grocery', 'market', 'store', 'shopping'],
        component: 'basket-handheld-lines.svg',
    },
    {
        id: 'basket-cart-speed',
        name: 'Speed Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'speed', 'fast', 'express', 'delivery', 'shopping', 'ecommerce', 'quick buy'],
        component: 'basket-cart-speed.svg',
    },
    {
        id: 'basket-handheld-dual-handle',
        name: 'Dual Handle Basket',
        category: 'basket',
        tags: ['basket', 'cart', 'dual handle', 'handles', 'grocery', 'shopping', 'store', 'supermarket', 'handheld'],
        component: 'basket-handheld-dual-handle.svg',
    },
    {
        id: 'basket-cart-simple',
        name: 'Simple Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'simple', 'minimal', 'shopping cart', 'store', 'shop', 'ecommerce', 'checkout'],
        component: 'basket-cart-simple.svg',
    },
    {
        id: 'basket-cart-shelf',
        name: 'Shopping Cart Shelf',
        category: 'basket',
        tags: ['basket', 'cart', 'shelf', 'rack', 'tray', 'shopping cart', 'supermarket', 'store', 'trolley'],
        component: 'basket-cart-shelf.svg',
    },
    {
        id: 'basket-cart-arrow-down',
        name: 'Cart Arrow Down',
        category: 'basket',
        tags: ['basket', 'cart', 'arrow down', 'add to cart', 'put in', 'download', 'insert', 'shopping', 'ecommerce'],
        component: 'basket-cart-arrow-down.svg',
    },
    {
        id: 'basket-cart-arrow-up',
        name: 'Cart Arrow Up',
        category: 'basket',
        tags: ['basket', 'cart', 'arrow up', 'remove from cart', 'upload', 'checkout', 'export', 'shopping', 'ecommerce'],
        component: 'basket-cart-arrow-up.svg',
    },
    {
        id: 'basket-cart-check-outline',
        name: 'Cart Check Outline',
        category: 'basket',
        tags: ['basket', 'cart', 'check', 'checkmark', 'approved', 'success', 'done', 'shopping cart', 'ecommerce'],
        component: 'basket-cart-check-outline.svg',
    },
    {
        id: 'basket-cart-check-solid',
        name: 'Cart Check Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'check', 'checkmark', 'solid', 'complete', 'success', 'order', 'shopping cart'],
        component: 'basket-cart-check-solid.svg',
    },
    {
        id: 'basket-cart-check',
        name: 'Cart Check',
        category: 'basket',
        tags: ['basket', 'cart', 'check', 'checkmark', 'tick', 'verified', 'shopping', 'store', 'ecommerce'],
        component: 'basket-cart-check.svg',
    },
    {
        id: 'basket-cart-cross-solid',
        name: 'Cart Cross Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'cross', 'x', 'cancel', 'remove', 'delete', 'solid', 'shopping cart'],
        component: 'basket-cart-cross-solid.svg',
    },
    {
        id: 'basket-round-arrow-down',
        name: 'Round Cart Arrow Down',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'arrow down', 'add', 'put in', 'shopping', 'ecommerce'],
        component: 'basket-round-arrow-down.svg',
    },
    {
        id: 'basket-round-empty',
        name: 'Round Cart Empty',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'empty', 'clear', 'shopping cart', 'ecommerce', 'minimal'],
        component: 'basket-round-empty.svg',
    },
    {
        id: 'basket-solid-fill',
        name: 'Solid Fill Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'solid', 'fill', 'loaded', 'package', 'full', 'shopping cart', 'ecommerce'],
        component: 'basket-solid-fill.svg',
    },
    {
        id: 'basket-round-fill',
        name: 'Round Cart Fill',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'fill', 'solid', 'loaded', 'item', 'shopping'],
        component: 'basket-round-fill.svg',
    },
    {
        id: 'basket-large-minimal',
        name: 'Large Cart Minimal',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'wide', 'minimal', 'solar', 'modern', 'shopping cart', 'ecommerce'],
        component: 'basket-large-minimal.svg',
    },
    {
        id: 'basket-large-slats',
        name: 'Large Cart Slats',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'slats', 'diagonal', 'solar', 'shopping cart', 'supermarket', 'ecommerce'],
        component: 'basket-large-slats.svg',
    },
    {
        id: 'basket-large-bars-solid',
        name: 'Large Cart Bars Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'bars', 'solid', 'vertical', 'solar', 'shopping cart', 'supermarket'],
        component: 'basket-large-bars-solid.svg',
    },
    {
        id: 'basket-large-bars',
        name: 'Large Cart Bars',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'bars', 'outline', 'vertical', 'solar', 'shopping cart', 'supermarket'],
        component: 'basket-large-bars.svg',
    },
    {
        id: 'basket-large-outline',
        name: 'Large Cart Outline',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'outline', 'clean', 'solar', 'minimalist', 'shopping cart', 'ecommerce'],
        component: 'basket-large-outline.svg',
    },
    {
        id: 'basket-large-dash',
        name: 'Large Cart Dash',
        category: 'basket',
        tags: ['basket', 'cart', 'large', 'dash', 'solar', 'modern', 'shopping cart', 'store', 'ecommerce'],
        component: 'basket-large-dash.svg',
    },
    {
        id: 'basket-cart-minus',
        name: 'Cart Minus',
        category: 'basket',
        tags: ['basket', 'cart', 'minus', 'remove', 'subtract', 'delete item', 'shopping', 'ecommerce', 'checkout'],
        component: 'basket-cart-minus.svg',
    },
    {
        id: 'basket-round-plus',
        name: 'Round Cart Plus',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'plus', 'add', 'insert', 'new item', 'shopping'],
        component: 'basket-round-plus.svg',
    },
    {
        id: 'basket-cart-plus-outline',
        name: 'Cart Plus Outline',
        category: 'basket',
        tags: ['basket', 'cart', 'plus', 'outline', 'add to cart', 'insert', 'solar', 'shopping cart', 'ecommerce'],
        component: 'basket-cart-plus-outline.svg',
    },
    {
        id: 'basket-cart-plus',
        name: 'Cart Plus',
        category: 'basket',
        tags: ['basket', 'cart', 'plus', 'add', 'add item', 'shopping', 'store', 'ecommerce', 'buy'],
        component: 'basket-cart-plus.svg',
    },
    {
        id: 'basket-round-handle',
        name: 'Round Cart Handle',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'handle', 'bar', 'shopping cart', 'ecommerce', 'trolley'],
        component: 'basket-round-handle.svg',
    },
    {
        id: 'basket-round-simple',
        name: 'Round Cart Simple',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'simple', 'classic', 'shopping cart', 'ecommerce', 'market'],
        component: 'basket-round-simple.svg',
    },
    {
        id: 'basket-cart-fast',
        name: 'Fast Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'fast', 'quick', 'speed', 'express', 'delivery', 'shopping', 'ecommerce'],
        component: 'basket-cart-fast.svg',
    },
    {
        id: 'basket-cart-classic',
        name: 'Classic Shopping Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'classic', 'standard', 'outline', 'store', 'shop', 'ecommerce', 'checkout'],
        component: 'basket-cart-classic.svg',
    },
    {
        id: 'basket-tote-smile',
        name: 'Smile Tote Basket',
        category: 'basket',
        tags: ['basket', 'cart', 'tote', 'smile', 'happy', 'bag', 'grocery', 'shopping', 'friendly'],
        component: 'basket-tote-smile.svg',
    },
    {
        id: 'basket-handheld-solid',
        name: 'Handheld Basket Solid',
        category: 'basket',
        tags: ['basket', 'cart', 'handheld', 'solid', 'grocery', 'supermarket', 'market', 'shopping', 'store'],
        component: 'basket-handheld-solid.svg',
    },
    {
        id: 'basket-trolley-grid',
        name: 'Trolley Grid Cart',
        category: 'basket',
        tags: ['basket', 'cart', 'trolley', 'grid', 'wire', 'supermarket', 'store', 'shopping cart', 'market'],
        component: 'basket-trolley-grid.svg',
    },
    {
        id: 'basket-round-arrow-up',
        name: 'Round Cart Arrow Up',
        category: 'basket',
        tags: ['basket', 'cart', 'round', 'badge', 'arrow up', 'checkout', 'export', 'shopping', 'ecommerce'],
        component: 'basket-round-arrow-up.svg',
    },
    {
        id: 'basket-cart-xmark',
        name: 'Cart X Mark',
        category: 'basket',
        tags: ['basket', 'cart', 'x mark', 'cross', 'remove', 'cancel', 'delete', 'shopping', 'ecommerce'],
        component: 'basket-cart-xmark.svg',
    },
    {
        id: "message-round-pending",
        name: "Round Message Pending",
        category: "message",
        tags: ["message","round","pending","dots","typing","chat","bubble","waiting","dialog"],
        component: "message-round-pending.svg",
    },
    {
        id: "message-round-lines-tail",
        name: "Round Message Lines Tail",
        category: "message",
        tags: ["message","round","lines","tail","text","chat","dialog","speech","conversation"],
        component: "message-round-lines-tail.svg",
    },
    {
        id: "message-envelope-half-solid",
        name: "Envelope Half Solid",
        category: "message",
        tags: ["message","envelope","mail","email","letter","half solid","inbox","post"],
        component: "message-envelope-half-solid.svg",
    },
    {
        id: "message-inbox-tray",
        name: "Message Inbox Tray",
        category: "message",
        tags: ["message","inbox","tray","box","archive","mail","storage","incoming"],
        component: "message-inbox-tray.svg",
    },
    {
        id: "message-square-chat",
        name: "Square Message Chat",
        category: "message",
        tags: ["message","square","chat","bubble","dialog","talk","speech","discussion"],
        component: "message-square-chat.svg",
    },
    {
        id: "message-circle-chart",
        name: "Circle Message Chart",
        category: "message",
        tags: ["message","circle","chart","analytics","poll","graph","data","feedback","stats"],
        component: "message-circle-chart.svg",
    },
    {
        id: "message-circle-chat",
        name: "Circle Message Chat",
        category: "message",
        tags: ["message","circle","chat","bubble","speech","dialog","talk","conversation"],
        component: "message-circle-chat.svg",
    },
    {
        id: "message-circle-dots-tail",
        name: "Circle Message Dots Tail",
        category: "message",
        tags: ["message","circle","dots","tail","typing","more","chat","comment","dialog"],
        component: "message-circle-dots-tail.svg",
    },
    {
        id: "message-circle-dots",
        name: "Circle Message Dots",
        category: "message",
        tags: ["message","circle","dots","typing","chat","speech bubble","conversation","ellipsis"],
        component: "message-circle-dots.svg",
    },
    {
        id: "message-circle-heart",
        name: "Circle Message Heart",
        category: "message",
        tags: ["message","circle","heart","like","favorite","love","appreciation","chat","feedback"],
        component: "message-circle-heart.svg",
    },
    {
        id: "message-circle-lines-full",
        name: "Circle Message Lines Full",
        category: "message",
        tags: ["message","circle","lines","full","text","chat","speech","note","dialog"],
        component: "message-circle-lines-full.svg",
    },
    {
        id: "message-circle-lines-smooth",
        name: "Circle Message Lines Smooth",
        category: "message",
        tags: ["message","circle","lines","smooth","tail","text","speech","chat","dialog"],
        component: "message-circle-lines-smooth.svg",
    },
    {
        id: "message-circle-lines-sharp",
        name: "Circle Message Lines Sharp",
        category: "message",
        tags: ["message","circle","lines","sharp","tail","text","chat","speech","dialog"],
        component: "message-circle-lines-sharp.svg",
    },
    {
        id: "message-circle-lines",
        name: "Circle Message Lines",
        category: "message",
        tags: ["message","circle","lines","text","chat","speech bubble","conversation","dialog"],
        component: "message-circle-lines.svg",
    },
    {
        id: "message-circle-notification",
        name: "Circle Message Notification",
        category: "message",
        tags: ["message","circle","notification","badge","alert","unread","bell","notice","chat"],
        component: "message-circle-notification.svg",
    },
    {
        id: "message-circle-pencil",
        name: "Circle Message Pencil",
        category: "message",
        tags: ["message","circle","pencil","edit","write","compose","draft","comment","chat"],
        component: "message-circle-pencil.svg",
    },
    {
        id: "message-circle-plus",
        name: "Circle Message Plus",
        category: "message",
        tags: ["message","circle","plus","add","new message","create","chat","compose"],
        component: "message-circle-plus.svg",
    },
    {
        id: "message-circle-refresh",
        name: "Circle Message Refresh",
        category: "message",
        tags: ["message","circle","refresh","sync","reload","update","repeat","chat","history"],
        component: "message-circle-refresh.svg",
    },
    {
        id: "message-circle-search",
        name: "Circle Message Search",
        category: "message",
        tags: ["message","circle","search","magnifier","find","lookup","filter","chat"],
        component: "message-circle-search.svg",
    },
    {
        id: "message-circle-shield",
        name: "Circle Message Shield",
        category: "message",
        tags: ["message","circle","shield","security","protected","encrypted","safe","privacy","chat"],
        component: "message-circle-shield.svg",
    },
    {
        id: "message-circle-open-tail",
        name: "Circle Message Open Tail",
        category: "message",
        tags: ["message","circle","open tail","bubble","chat","dialog","outline","speech"],
        component: "message-circle-open-tail.svg",
    },
    {
        id: "message-circle-outline",
        name: "Circle Message Outline",
        category: "message",
        tags: ["message","circle","outline","bubble","classic","chat","dialog","speech"],
        component: "message-circle-outline.svg",
    },
    {
        id: "message-envelope-open-bold",
        name: "Envelope Open Bold",
        category: "message",
        tags: ["message","envelope","open","bold","mail","email","letter","read","inbox"],
        component: "message-envelope-open-bold.svg",
    },
    {
        id: "message-envelope-open",
        name: "Envelope Open",
        category: "message",
        tags: ["message","envelope","open","mail","email","letter","read","inbox"],
        component: "message-envelope-open.svg",
    },
    {
        id: "message-square-pending",
        name: "Square Message Pending",
        category: "message",
        tags: ["message","square","pending","dots","typing","waiting","chat","dialog"],
        component: "message-square-pending.svg",
    },
    {
        id: "message-round-solid",
        name: "Round Message Solid",
        category: "message",
        tags: ["message","round","solid","filled","bubble","chat","speech","dialog"],
        component: "message-round-solid.svg",
    },
    {
        id: "message-square-search-corner",
        name: "Square Message Search Corner",
        category: "message",
        tags: ["message","square","search","corner","find","magnifier","lookup","chat"],
        component: "message-square-search-corner.svg",
    },
    {
        id: "message-circle-smile",
        name: "Circle Message Smile",
        category: "message",
        tags: ["message","circle","smile","happy","emoji","feedback","satisfaction","chat"],
        component: "message-circle-smile.svg",
    },
    {
        id: "message-square-smile",
        name: "Square Message Smile",
        category: "message",
        tags: ["message","square","smile","happy","emoji","feedback","satisfaction","chat"],
        component: "message-square-smile.svg",
    },
    {
        id: "message-square-arrow-down",
        name: "Square Message Arrow Down",
        category: "message",
        tags: ["message","square","arrow down","incoming","receive","download","inbox","chat"],
        component: "message-square-arrow-down.svg",
    },
    {
        id: "message-square-block",
        name: "Square Message Block",
        category: "message",
        tags: ["message","square","block","ban","prohibited","cancel","restrict","chat"],
        component: "message-square-block.svg",
    },
    {
        id: "message-square-check",
        name: "Square Message Check",
        category: "message",
        tags: ["message","square","check","checkmark","approved","verified","done","read","success"],
        component: "message-square-check.svg",
    },
    {
        id: "message-square-dots-squircle",
        name: "Square Message Dots Squircle",
        category: "message",
        tags: ["message","square","dots","squircle","rounded","typing","chat","dialog"],
        component: "message-square-dots-squircle.svg",
    },
    {
        id: "message-square-dots-tech",
        name: "Square Message Dots Tech",
        category: "message",
        tags: ["message","square","dots","tech","segmented","typing","chat","dialog"],
        component: "message-square-dots-tech.svg",
    },
    {
        id: "message-square-dots",
        name: "Square Message Dots",
        category: "message",
        tags: ["message","square","dots","typing","more","chat","dialog","speech bubble"],
        component: "message-square-dots.svg",
    },
    {
        id: "message-square-exclamation",
        name: "Square Message Exclamation",
        category: "message",
        tags: ["message","square","exclamation","alert","warning","important","urgent","notice"],
        component: "message-square-exclamation.svg",
    },
    {
        id: "message-square-heart",
        name: "Square Message Heart",
        category: "message",
        tags: ["message","square","heart","like","favorite","love","feedback","chat"],
        component: "message-square-heart.svg",
    },
    {
        id: "message-square-image",
        name: "Square Message Image",
        category: "message",
        tags: ["message","square","image","picture","photo","media","attachment","chat"],
        component: "message-square-image.svg",
    },
    {
        id: "message-square-lines-tech",
        name: "Square Message Lines Tech",
        category: "message",
        tags: ["message","square","lines","tech","segmented","text","chat","dialog"],
        component: "message-square-lines-tech.svg",
    },
    {
        id: "message-square-lines-squircle",
        name: "Square Message Lines Squircle",
        category: "message",
        tags: ["message","square","lines","squircle","rounded","text","chat","dialog"],
        component: "message-square-lines-squircle.svg",
    },
    {
        id: "message-square-list",
        name: "Square Message List",
        category: "message",
        tags: ["message","square","list","bullet list","tasks","items","chat","notes"],
        component: "message-square-list.svg",
    },
    {
        id: "message-square-notification",
        name: "Square Message Notification",
        category: "message",
        tags: ["message","square","notification","badge","unread","alert","notice","chat"],
        component: "message-square-notification.svg",
    },
    {
        id: "message-square-pencil",
        name: "Square Message Pencil",
        category: "message",
        tags: ["message","square","pencil","edit","write","compose","draft","chat"],
        component: "message-square-pencil.svg",
    },
    {
        id: "message-square-plus",
        name: "Square Message Plus",
        category: "message",
        tags: ["message","square","plus","add","new message","create","compose","chat"],
        component: "message-square-plus.svg",
    },
    {
        id: "message-square-question",
        name: "Square Message Question",
        category: "message",
        tags: ["message","square","question","help","faq","support","ask","query","chat"],
        component: "message-square-question.svg",
    },
    {
        id: "message-square-refresh",
        name: "Square Message Refresh",
        category: "message",
        tags: ["message","square","refresh","sync","reload","retry","update","chat"],
        component: "message-square-refresh.svg",
    },
    {
        id: "message-square-search",
        name: "Square Message Search",
        category: "message",
        tags: ["message","square","search","magnifier","find","lookup","filter","chat"],
        component: "message-square-search.svg",
    },
    {
        id: "message-square-shield",
        name: "Square Message Shield",
        category: "message",
        tags: ["message","square","shield","security","protected","encrypted","safe","chat"],
        component: "message-square-shield.svg",
    },
    {
        id: "message-square-outline",
        name: "Square Message Outline",
        category: "message",
        tags: ["message","square","outline","bubble","chat","dialog","speech","empty"],
        component: "message-square-outline.svg",
    },
    {
        id: "message-square-xmark",
        name: "Square Message X Mark",
        category: "message",
        tags: ["message","square","x mark","cancel","close","delete","remove","chat"],
        component: "message-square-xmark.svg",
    },
    {
        id: "message-envelope-solid",
        name: "Envelope Solid",
        category: "message",
        tags: ["message","envelope","solid","mail","email","letter","post","inbox"],
        component: "message-envelope-solid.svg",
    },
    {
        id: "message-square-dots-rounded",
        name: "Square Message Dots Rounded",
        category: "message",
        tags: ["message","square","dots","rounded","typing","chat","dialog","speech"],
        component: "message-square-dots-rounded.svg",
    },
    {
        id: "message-bubble-lines-tail",
        name: "Message Bubble Lines Tail",
        category: "message",
        tags: ["message","bubble","lines","tail","text","comment","chat","dialog"],
        component: "message-bubble-lines-tail.svg",
    },
    {
        id: "message-paper-plane",
        name: "Message Paper Plane",
        category: "message",
        tags: ["message","paper plane","send","submit","dispatch","telegram","outbox","chat"],
        component: "message-paper-plane.svg",
    },
    {
        id: "message-paper-plane-duotone",
        name: "Message Paper Plane Duotone",
        category: "message",
        tags: ["message","paper plane","duotone","send","submit","telegram","outbox"],
        component: "message-paper-plane-duotone.svg",
    },
    {
        id: "message-envelope-curved-solid",
        name: "Envelope Curved Solid",
        category: "message",
        tags: ["message","envelope","curved","solid","mail","email","letter","post"],
        component: "message-envelope-curved-solid.svg",
    },
    {
        id: "message-envelope-outline",
        name: "Envelope Outline",
        category: "message",
        tags: ["message","envelope","outline","mail","email","letter","post","inbox"],
        component: "message-envelope-outline.svg",
    },
    {
        id: "message-envelope-bold",
        name: "Envelope Bold",
        category: "message",
        tags: ["message","envelope","bold","mail","email","letter","post","inbox"],
        component: "message-envelope-bold.svg",
    },
    {
        id: "message-envelope-layered-solid",
        name: "Envelope Layered Solid",
        category: "message",
        tags: ["message","envelope","layered","solid","mail","email","letter","post"],
        component: "message-envelope-layered-solid.svg",
    },
    {
        id: "message-square-lines-rounded",
        name: "Square Message Lines Rounded",
        category: "message",
        tags: ["message","square","lines","rounded","text","chat","dialog","speech"],
        component: "message-square-lines-rounded.svg",
    },
    {
        id: "message-square-lines-tail",
        name: "Square Message Lines Tail",
        category: "message",
        tags: ["message","square","lines","tail","text","speech bubble","chat","dialog"],
        component: "message-square-lines-tail.svg",
    },
    {
        id: "user-check-solar",
        name: "User Check Solar",
        category: "user",
        tags: ["user","check","checkmark","solar","verified","approved","account","profile"],
        component: "user-check-solar.svg",
    },
    {
        id: "user-check",
        name: "User Check",
        category: "user",
        tags: ["user","check","checkmark","verified","approved","active","account","profile"],
        component: "user-check.svg",
    },
    {
        id: "user-circle-solar",
        name: "User Circle Solar",
        category: "user",
        tags: ["user","circle","solar","avatar","profile","account","person","member"],
        component: "user-circle-solar.svg",
    },
    {
        id: "user-circle-classic",
        name: "User Circle Classic",
        category: "user",
        tags: ["user","circle","classic","avatar","profile","account","person","member"],
        component: "user-circle-classic.svg",
    },
    {
        id: "user-xmark-circle",
        name: "User X Mark Circle",
        category: "user",
        tags: ["user","x mark","circle","remove","delete","ban","block","cancel","account"],
        component: "user-xmark-circle.svg",
    },
    {
        id: "user-hand-up",
        name: "User Hand Up",
        category: "user",
        tags: ["user","hand up","raise hand","volunteer","question","vote","participate","person"],
        component: "user-hand-up.svg",
    },
    {
        id: "user-hands",
        name: "User Hands",
        category: "user",
        tags: ["user","hands","care","support","welcome","community","customer","person"],
        component: "user-hands.svg",
    },
    {
        id: "user-heart-solar",
        name: "User Heart Solar",
        category: "user",
        tags: ["user","heart","solar","favorite","like","follower","love","loyalty","profile"],
        component: "user-heart-solar.svg",
    },
    {
        id: "user-heart",
        name: "User Heart",
        category: "user",
        tags: ["user","heart","favorite","like","follower","love","loyalty","profile"],
        component: "user-heart.svg",
    },
    {
        id: "user-id-card",
        name: "User ID Card",
        category: "user",
        tags: ["user","id","card","badge","credentials","identity","pass","employee","license"],
        component: "user-id-card.svg",
    },
    {
        id: "user-lock-keyhole",
        name: "User Lock Keyhole",
        category: "user",
        tags: ["user","lock","keyhole","security","password","protected","access","privacy"],
        component: "user-lock-keyhole.svg",
    },
    {
        id: "user-lock",
        name: "User Lock",
        category: "user",
        tags: ["user","lock","security","padlock","private","blocked","auth","permissions"],
        component: "user-lock.svg",
    },
    {
        id: "user-minus-solar",
        name: "User Minus Solar",
        category: "user",
        tags: ["user","minus","solar","remove","delete","sub","unfollow","account"],
        component: "user-minus-solar.svg",
    },
    {
        id: "user-minus-circle",
        name: "User Minus Circle",
        category: "user",
        tags: ["user","minus","circle","remove","delete","sub","unfollow","account"],
        component: "user-minus-circle.svg",
    },
    {
        id: "user-minus",
        name: "User Minus",
        category: "user",
        tags: ["user","minus","remove","delete","sub","unfollow","account","profile"],
        component: "user-minus.svg",
    },
    {
        id: "user-pen-diagonal",
        name: "User Pen Diagonal",
        category: "user",
        tags: ["user","pen","diagonal","edit","write","modify","update","profile"],
        component: "user-pen-diagonal.svg",
    },
    {
        id: "user-pen",
        name: "User Pen",
        category: "user",
        tags: ["user","pen","pencil","edit","write","modify","update","profile","author"],
        component: "user-pen.svg",
    },
    {
        id: "user-plus-circle",
        name: "User Plus Circle",
        category: "user",
        tags: ["user","plus","circle","add","create","register","invite","new user","account"],
        component: "user-plus-circle.svg",
    },
    {
        id: "user-plus-solar",
        name: "User Plus Solar",
        category: "user",
        tags: ["user","plus","solar","add","create","register","invite","new user","account"],
        component: "user-plus-solar.svg",
    },
    {
        id: "user-question-solid",
        name: "User Question Solid",
        category: "user",
        tags: ["user","question","solid","help","support","unknown","faq","profile"],
        component: "user-question-solid.svg",
    },
    {
        id: "user-question",
        name: "User Question",
        category: "user",
        tags: ["user","question","help","support","unknown","faq","profile","inquiry"],
        component: "user-question.svg",
    },
    {
        id: "user-refresh",
        name: "User Refresh",
        category: "user",
        tags: ["user","refresh","sync","reload","switch","rotate","change account","profile"],
        component: "user-refresh.svg",
    },
    {
        id: "user-rounded",
        name: "User Rounded",
        category: "user",
        tags: ["user","rounded","avatar","profile","account","person","member","simple"],
        component: "user-rounded.svg",
    },
    {
        id: "user-search-zoom",
        name: "User Search Zoom",
        category: "user",
        tags: ["user","search","zoom","magnifier","find","lookup","filter","account"],
        component: "user-search-zoom.svg",
    },
    {
        id: "user-search",
        name: "User Search",
        category: "user",
        tags: ["user","search","magnifier","find","lookup","filter","account","profile"],
        component: "user-search.svg",
    },
    {
        id: "user-shield-star",
        name: "User Shield Star",
        category: "user",
        tags: ["user","shield","star","admin","moderator","security","role","superadmin","badge"],
        component: "user-shield-star.svg",
    },
    {
        id: "user-shield-badge",
        name: "User Shield Badge",
        category: "user",
        tags: ["user","shield","badge","security","protected","verified","role","permissions"],
        component: "user-shield-badge.svg",
    },
    {
        id: "user-shield",
        name: "User Shield",
        category: "user",
        tags: ["user","shield","protection","security","defense","safe","permissions","profile"],
        component: "user-shield.svg",
    },
    {
        id: "user-speak",
        name: "User Speak",
        category: "user",
        tags: ["user","speak","sound","voice","talk","presenter","audio","podcast","commentator"],
        component: "user-speak.svg",
    },
    {
        id: "user-solid",
        name: "User Solid",
        category: "user",
        tags: ["user","solid","filled","avatar","profile","account","person","member"],
        component: "user-solid.svg",
    },
    {
        id: "user-xmark-corner",
        name: "User X Mark Corner",
        category: "user",
        tags: ["user","x mark","corner","cancel","remove","delete","dismiss","account"],
        component: "user-xmark-corner.svg",
    },
    {
        id: "user-xmark-badge",
        name: "User X Mark Badge",
        category: "user",
        tags: ["user","x mark","badge","cancel","remove","delete","ban","block","account"],
        component: "user-xmark-badge.svg",
    },
    {
        id: "user-xmark",
        name: "User X Mark",
        category: "user",
        tags: ["user","x mark","cancel","remove","delete","close","unassign","profile"],
        component: "user-xmark.svg",
    },
];
